// Pipe colors
#define	PIPE_COLOR_GREY		COLOR_WHITE	// Yes white is grey
#define	PIPE_COLOR_RED		COLOR_RED
#define	PIPE_COLOR_BLUE		COLOR_BLUE
#define	PIPE_COLOR_CYAN		COLOR_CYAN
#define	PIPE_COLOR_GREEN	COLOR_LIME
#define	PIPE_COLOR_YELLOW	COLOR_YELLOW_GOLD
#define	PIPE_COLOR_BLACK	COLOR_GRAY_DARK
#define	PIPE_COLOR_PURPLE	COLOR_VIOLET
