//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2026 Citadel Station Developers           *//

/**
 * Runs multiple generator cycles on a buffer.
 */
/datum/jigsaw_chain_generator_config
	var/prepared = FALSE

	/**
	 * Tile budget.
	 * * Overrules [tile_budget_ratio] if set.
	 * * Limits the total number of tiles generated by the chain-generation.
	 */
	var/tile_budget
	/**
	 * Tile budget as a ratio of available tiles.
	 * * Limits the total number of tiles generated by the chain-generation.
	 */
	var/tile_budget_ratio
	/**
	 * Custom budgets, key-value list of string-number.
	 * * This is applied in parallel with the existing generator config budgets, so
	 *   if this is lower, this is applied instead of that.
	 */
	var/list/custom_budgets = list()

/datum/jigsaw_chain_generator_config/proc/prepare()
	SHOULD_NOT_OVERRIDE(TRUE)

	if(prepared)
		return
	prepared = TRUE
	prepare_impl()

/datum/jigsaw_chain_generator_config/proc/prepare_impl()
	PROTECTED_PROC(TRUE)

/datum/jigsaw_chain_generator_config/proc/get_generator_configs() as /list
	SHOULD_CALL_PARENT(TRUE)
	prepare()

#warn impl

/datum/jigsaw_chain_generator_config/literally_everything
