//GENERAL
#define COLOR_HALF_TRANSPARENT_BLACK	"#0000007A"
#define COLOR_NAVY						"#000080"

// Color defines used by the assembly detailer.
#define COLOR_ASSEMBLY_HOT_PINK	"#FF69B4"

///MISC
#define COLOR_FLOORTILE_GRAY			"#8D8B8B"

///INTERFACE

#define COLOR_DARKMODE_BACKGROUND		"#202020"
#define COLOR_DARKMODE_DARKBACKGROUND	"#171717"
#define COLOR_DARKMODE_TEXT				"#a4bad6"
