//! GENERAL
#define COLOR_WHITE                  "#FFFFFF"
#define COLOR_VERY_LIGHT_GRAY        "#EEEEEE"
#define COLOR_GRAY80                 "#CCCCCC"
#define COLOR_SILVER                 "#C0C0C0"
#define COLOR_GRAY                   "#808080"
#define COLOR_GRAY40                 "#666666"
#define COLOR_GRAY20                 "#333333"
#define COLOR_GRAY15                 "#151515"
#define COLOR_HALF_TRANSPARENT_BLACK "#0000007A"
#define COLOR_BLACK                  "#000000"
#define COLOR_RED_LIGHT              "#FF3333"
#define COLOR_RED                    "#FF0000"
#define COLOR_DARK_RED               "#AA0000"
#define COLOR_MAROON                 "#800000"
#define COLOR_DARK_ORANGE            "#B95A00"
#define COLOR_ORANGE                 "#FF9900"
#define COLOR_YELLOW                 "#FFFF00"
#define COLOR_GOLD                   "#FFCC33"
#define COLOR_OLIVE                  "#808000"
#define COLOR_LIME                   "#00FF00"
#define COLOR_BOTTLE_GREEN           "#1F6B4F"
#define COLOR_GREEN                  "#008000"
#define COLOR_CYAN                   "#00FFFF"
#define COLOR_TEAL                   "#008080"
#define COLOR_BLUE                   "#0000FF"
#define COLOR_NAVY                   "#000080"
#define COLOR_PINK                   "#FF00FF"
#define COLOR_PURPLE                 "#800080"
#define COLOR_GUNMETAL               "#545C68"
#define COLOR_WALL_GUNMETAL          "#353A42"
#define COLOR_STEEL                  "#A8B0B2"
#define COLOR_LUMINOL                "#66FFFF"
#define COLOR_BEIGE                  "#CEB689"
#define COLOR_BLUE_GRAY              "#6A97B0"
#define COLOR_SKY_BLUE               "#5CA1CC"
#define COLOR_BROWN                  "#B19664"
#define COLOR_DARK_BROWN             "#917448"
#define COLOR_CHESTNUT               "#996633"
#define COLOR_COPPER                 "#b87333"
#define COLOR_BEASTY_BROWN           "#663300"
#define COLOR_GREEN_GRAY             "#8DAF6A"
#define COLOR_RED_GRAY               "#AA5F61"
#define COLOR_PALE_BLUE_GRAY         "#8BBBD5"
#define COLOR_PALE_GREEN_GRAY        "#AED18B"
#define COLOR_PALE_RED_GRAY          "#CC9090"
#define COLOR_PALE_PURPLE_GRAY       "#BDA2BA"
#define COLOR_PURPLE_GRAY            "#A2819E"
#define COLOR_DEEP_SKY_BLUE          "#00E1ff"

//! CIRCUITS - ASSEMBLY DETAILER
#define COLOR_ASSEMBLY_BLACK    "#545454"
#define COLOR_ASSEMBLY_BGRAY    "#9497AB"
#define COLOR_ASSEMBLY_WHITE    "#E2E2E2"
#define COLOR_ASSEMBLY_RED      "#CC4242"
#define COLOR_ASSEMBLY_ORANGE   "#E39751"
#define COLOR_ASSEMBLY_BEIGE    "#AF9366"
#define COLOR_ASSEMBLY_BROWN    "#97670E"
#define COLOR_ASSEMBLY_GOLD     "#AA9100"
#define COLOR_ASSEMBLY_YELLOW   "#CECA2B"
#define COLOR_ASSEMBLY_GURKHA   "#999875"
#define COLOR_ASSEMBLY_LGREEN   "#789876"
#define COLOR_ASSEMBLY_GREEN    "#44843C"
#define COLOR_ASSEMBLY_LBLUE    "#5D99BE"
#define COLOR_ASSEMBLY_BLUE     "#38559E"
#define COLOR_ASSEMBLY_PURPLE   "#6F6192"
#define COLOR_ASSEMBLY_HOT_PINK "#FF69B4"

//! MISC
#define COLOR_ASTEROID_ROCK  "#735555"
#define COLOR_DIAMOND        "#d8d4ea"
#define COLOR_FLOORTILE_GRAY "#8D8B8B"

//! INTERFACE
#define COLOR_INPUT_DISABLED          "#F0F0F0"
#define COLOR_INPUT_ENABLED           "#D3B5B5"
#define COLOR_DARKMODE_BACKGROUND     "#202020"
#define COLOR_DARKMODE_DARKBACKGROUND "#171717"
#define COLOR_DARKMODE_TEXT           "#a4bad6"

//! WOOD
#define WOOD_COLOR_GENERIC   "#9c5930"
#define WOOD_COLOR_BOARD     "#d5a66e"
#define WOOD_COLOR_RICH      "#792f27"
#define WOOD_COLOR_PALE      "#d2bc9d"
#define WOOD_COLOR_PALE2     "#e6d2ba"
#define WOOD_COLOR_BLACK     "#332521"
#define WOOD_COLOR_CHOCOLATE "#543c30"
#define WOOD_COLOR_YELLOW    "#e3994e"
#define WOOD_COLOR_SIF       "#0099cc"
#define WOOD_COLOR_HARD      "#6f432a"


//! FLUIDS
#define COLOR_LIQUID_WATER "#99f5ff"
#define COLOR_ICE          "#eef5ff"
