/datum/lore/character_background/origin/species/tajaran/ahdomai
	name = "Ahdomai"
	id = "origin_tajaran_adhomai"
	desc = "Ahdomai, the homeworld of the Tajaran peoples. It is the fourth planet from S’randarr. It is a cold and icy world, having just suffered a brutal ice age it’s inhabitants call, “The Frost”. The planet still is suffering from almost perpetual snowfall and extremely low temperatures which are only survivable due to massive generators and natural geothermal sources. On the galactic stage the Confederate Commonwealth represents the Tajara, but the situation planetside is far more complicated. The Confederate Commonwealth is actually made up of numerous city states, with only a few global “super”powers, all vying for power and their own ideals."

/datum/lore/character_background/origin/species/tajaran/ccss
	name = "CCSS"
	id = "origin_tajaran_ccss"
	desc = "CCSS, a major space station and port orbiting Ahdomai. Originally created in partnership with the Orion Confederation, this station was intended to serve as a major spaceport, headquarters for the Confederate Commonwealth, and base for the peacekeeping forces of the Confederate Commonwealth. Over time, the station grew in size and became a symbol of unity displayed by the Tajara. The station now is massive, with a relative population of 3,000 permanent residents, 5,000 temporary residents, and a maximum capacity of 20,000. The station follows galactic treaties and the laws of the Confederate Commonwealth, and is the bustling port connecting Tajara to the stars. It’s extremely multicultural and houses embassies to numerous other galactic nations and offices for the many megacorporations looking to invest in Tajaran opportunities. If a Tajara wanted to go offplanet, they’d have gone through this station."

/datum/lore/character_background/origin/species/tajaran/raskara
	name = "Raskara"
	id = "origin_tajaran_raskara"
	desc = "Raskara Moon Habitats, a minor collection of habitats created by the Confederate Commonwealth. The moon itself lacks an atmosphere, water and it has no tectonic or volcanic activity. The habitats on the moon were originally created to test the viability of growing crops native to Ahdomai offworld, but soon evolved from a scientific base to a mining port. With a small stable food supply and a port created, corporations began buying mining rights on the moon. Small bases and numerous autonomous mining droids were cropping up all over the surface along with a few major habitats for those living on the moon to be funded by the private companies with permission from the Confederate Commonwealth. Today Tajara living on Raskara have prospered and grown enough to warrant having their own representatives in the Council of Holds and Ahdomian Parliament, one of the only two offworld “holds” officially recognized by the Confederate Commonwealth."

/datum/lore/character_background/origin/species/tajaran/hrozamal
	name = "Hro'zamal"
	id = "origin_tajaran_hrozamal"
	desc = "Hro'zamal, a colony in the nearby Nrrahrahul system, the second planet from its star. The planet is covered in oceans, with the remaining landmass dominated by lush jungles except for the poles that possess a subtropical climate. It was first settled and maintained as a research and military base which grew until it was recognized as the planet’s capital and renamed to Muldhir in 2532.  Agriculture and plantations have become the staple exports of the colony. Most of Hro’zamal remains unexplored, with few outposts and settlements outside of the central city scattered across the jungle. A majority of the settlers hail from the PRA, and the rough,hostile, and unfamiliar environment of Hro'zamal has led to a major importance on collectivism, family, and work ethics. The colony is the first proper Tajaran attempt at settling a world outside of their home system.  Tajara on Hro’zamal have their own representatives in the Council of Holds and Ahdomian Parliament, one of the only two offworld “holds” officially recognized by the Confederate Commonwealth."
