/obj/machinery/point_redemption_vendor/mining
	name = "mining equipment vendor"
	desc = "An equipment vendor for miners, points collected at an ore redemption machine can be spent here."
	icon = 'icons/machinery/point_redemption_vendor/mining.dmi'
	icon_state = "vendor"
	icon_state_append_deny = "-deny"
	icon_state_append_open = "-open"
	icon_state_append_off = "-off"
	point_type = POINT_REDEMPTION_TYPE_MINING
	circuit = /obj/item/circuitboard/point_redemption_vendor/mining
	prize_list = list(
		new /datum/point_redemption_item("1 Marker Beacon",				/obj/item/stack/marker_beacon,										10),
		new /datum/point_redemption_item("10 Marker Beacons",			/obj/item/stack/marker_beacon/ten,									100),
		new /datum/point_redemption_item("30 Marker Beacons",			/obj/item/stack/marker_beacon/thirty,								300),
		new /datum/point_redemption_item("Whiskey",						/obj/item/reagent_containers/food/drinks/bottle/whiskey,		125),
		new /datum/point_redemption_item("Absinthe",					/obj/item/reagent_containers/food/drinks/bottle/absinthe,	125),
		new /datum/point_redemption_item("Hard Root Beer",				/obj/item/reagent_containers/food/drinks/bottle/small/alcsassafras,	70),
		new /datum/point_redemption_item("Special Blend Whiskey",						/obj/item/reagent_containers/food/drinks/bottle/specialwhiskey,		250),
		new /datum/point_redemption_item("Random Booze",						/obj/random/alcohol,		125),
		new /datum/point_redemption_item("Cigar",						/obj/item/clothing/mask/smokable/cigarette/cigar/havana,			150),
		new /datum/point_redemption_item("Root Beer",					/obj/item/reagent_containers/food/drinks/bottle/small/sassafras, 50),
		new /datum/point_redemption_item("Sarsaparilla",				/obj/item/reagent_containers/food/drinks/bottle/small/sarsaparilla, 50),
		new /datum/point_redemption_item("Soap",						/obj/item/soap/nanotrasen,									200),
		new /datum/point_redemption_item("Laser Pointer",				/obj/item/laser_pointer,										900),
		new /datum/point_redemption_item("Geiger Counter",				/obj/item/geiger_counter,											750),
		new /datum/point_redemption_item("Plush Toy",					/obj/random/plushie,												300),
		new /datum/point_redemption_item("GPS Device",					/obj/item/gps/mining,										100),
		new /datum/point_redemption_item("Portable Fuel Can",			/obj/item/reagent_containers/portable_fuelcan,		250),
		// TODO new /datum/point_redemption_item("Advanced Scanner",	/obj/item/t_scanner/adv_mining_scanner,						800),
		new /datum/point_redemption_item("Fulton Beacon",				/obj/item/fulton_core,												500),
		new /datum/point_redemption_item("Shelter Capsule",				/obj/item/survivalcapsule,									500),
		// TODO new /datum/point_redemption_item("Explorer's Webbing",	/obj/item/storage/belt/mining,										500),
		new /datum/point_redemption_item("500 Point Transfer Card",		/obj/item/point_redemption_voucher/preloaded/mining/c500,							500),
		new /datum/point_redemption_item("1000 Point Transfer Card",	/obj/item/point_redemption_voucher/preloaded/mining/c1000,							1000),
		new /datum/point_redemption_item("2000 Point Transfer Card",	/obj/item/point_redemption_voucher/preloaded/mining/c2000,							2000),
		new /datum/point_redemption_item("3000 Point Transfer Card",	/obj/item/point_redemption_voucher/preloaded/mining/c3000,							3000),
		new /datum/point_redemption_item("Umbrella",					/obj/item/melee/umbrella/random,								200),
		new /datum/point_redemption_item("Survival Medipen",			/obj/item/reagent_containers/hypospray/autoinjector/miner,	500),
		new /datum/point_redemption_item("Mini-Translocator",			/obj/item/perfect_tele/one_beacon,							1200),
		// new /datum/point_redemption_item("Kinetic Crusher",			/obj/item/twohanded/required/kinetic_crusher,						750),
		new /datum/point_redemption_item("Kinetic Accelerator",			/obj/item/gun/projectile/energy/kinetic_accelerator,					900),
		new /datum/point_redemption_item("Resonator",					/obj/item/resonator,												900),
		new /datum/point_redemption_item("Fulton Pack",					/obj/item/extraction_pack,											1200),
		new /datum/point_redemption_item("Wormhole Fulton Pack",					/obj/item/extraction_pack/wormhole,											1750),
		new /datum/point_redemption_item("Silver Pickaxe",				/obj/item/pickaxe/silver,									1200),
		new /datum/point_redemption_item("Climbing Pick",				/obj/item/pickaxe/icepick,									2200),
		//new /datum/point_redemption_item("Mining Conscription Kit",	/obj/item/storage/backpack/duffelbag/mining_conscript,				1000),
		new /datum/point_redemption_item("Diamond Pickaxe",				/obj/item/pickaxe/diamond,									2000),
		new /datum/point_redemption_item("Advanced Ore Scanner",				/obj/item/mining_scanner/advanced,										2000),
		new /datum/point_redemption_item("100 Thalers",					/obj/item/spacecash/c100,									5000),
		new /datum/point_redemption_item("1000 Thalers",					/obj/item/spacecash/c1000,									50000),
		new /datum/point_redemption_item("Hardsuit - Control Module",	/obj/item/hardsuit/industrial,									2000),
		new /datum/point_redemption_item("Hardsuit - Plasma Cutter",		/obj/item/hardsuit_module/device/plasmacutter,						800),
		new /datum/point_redemption_item("Hardsuit - Drill",				/obj/item/hardsuit_module/device/drill,								5000),
		new /datum/point_redemption_item("Hardsuit - Ore Scanner",		/obj/item/hardsuit_module/device/orescanner,								1000),
		new /datum/point_redemption_item("Hardsuit - Material Scanner",	/obj/item/hardsuit_module/vision/material,								500),
		new /datum/point_redemption_item("Hardsuit - Maneuvering Jets",	/obj/item/hardsuit_module/maneuvering_jets,								1250),
		new /datum/point_redemption_item("Hardsuit - Intelligence Storage",	/obj/item/hardsuit_module/ai_container,								2500),
		new /datum/point_redemption_item("Hardsuit - Smoke Bomb Deployer",	/obj/item/hardsuit_module/grenade_launcher/smoke,					2000),
		new /datum/point_redemption_item("Industrial Equipment - Phoron Bore",	/obj/item/gun/projectile/magnetic/matfed,						3000),
		new /datum/point_redemption_item("Industrial Equipment - Sheet-Snatcher",/obj/item/storage/bag/sheetsnatcher,				500),
		new /datum/point_redemption_item("Repurposed Equipment - Mining Carbine",	/obj/item/gun/projectile/energy/gun/miningcarbine,						5000),
		new /datum/point_redemption_item("Digital Tablet - Standard",	/obj/item/modular_computer/tablet/preset/custom_loadout/standard,	500),
		new /datum/point_redemption_item("Digital Tablet - Advanced",	/obj/item/modular_computer/tablet/preset/custom_loadout/advanced,	1000),
		new /datum/point_redemption_item("Super Resonator",				/obj/item/resonator/upgraded,										2500),
		new /datum/point_redemption_item("Jump Boots",					/obj/item/clothing/shoes/bhop,										2500),
		new /datum/point_redemption_item("Luxury Shelter Capsule",		/obj/item/survivalcapsule/luxury,							3100),
		new /datum/point_redemption_item("KA White Tracer Rounds",		/obj/item/ka_modkit/tracer,								125),
		new /datum/point_redemption_item("KA Adjustable Tracer Rounds",	/obj/item/ka_modkit/tracer/adjustable,					175),
		new /datum/point_redemption_item("KA Super Chassis",			/obj/item/ka_modkit/chassis_mod,							250),
		new /datum/point_redemption_item("KA Hyper Chassis",			/obj/item/ka_modkit/chassis_mod/orange,					300),
		new /datum/point_redemption_item("KA Range Increase",			/obj/item/ka_modkit/range,								1000),
		new /datum/point_redemption_item("KA Cooldown Decrease",		/obj/item/ka_modkit/cooldown,							1200),
		new /datum/point_redemption_item("KA Capacity Increase",		/obj/item/ka_modkit/capacity,							1500),
		new /datum/point_redemption_item("KA Holster",				/obj/item/clothing/accessory/holster/waist/kinetic_accelerator,			350),
		new /datum/point_redemption_item("Fine Excavation Kit - Chisels",/obj/item/storage/excavation,								500),
		new /datum/point_redemption_item("Fine Excavation Kit - Measuring Tape",/obj/item/measuring_tape,							125),
		new /datum/point_redemption_item("Fine Excavation Kit - Hand Pick",/obj/item/pickaxe/hand,									375),
		new /datum/point_redemption_item("Explosive Excavation Kit - Plastic Charge",/obj/item/plastique/seismic/locked,					1500),
		new /datum/point_redemption_item("Injector (L) - Glucose",/obj/item/reagent_containers/hypospray/autoinjector/biginjector/glucose,	500),
		new /datum/point_redemption_item("Injector (L) - Panacea",/obj/item/reagent_containers/hypospray/autoinjector/biginjector/purity,	500),
		new /datum/point_redemption_item("Injector (L) - Trauma",/obj/item/reagent_containers/hypospray/autoinjector/biginjector/brute,	500),
		new /datum/point_redemption_item("Nanopaste Tube",				/obj/item/stack/nanopaste,											1000),
		new /datum/point_redemption_item("Defense Equipment - Smoke Bomb",/obj/item/grenade/simple/smoke,								100),
		new /datum/point_redemption_item("Defense Equipment - Razor Drone Deployer",/obj/item/grenade/simple/spawner/manhacks/station/locked,	1000),
		new /datum/point_redemption_item("Defense Equipment - Sentry Drone Deployer",/obj/item/grenade/simple/spawner/ward,			1500),
		new /datum/point_redemption_item("Defense Equipment - Plasteel Machete",	/obj/item/clothing/accessory/holster/machete/occupied,				500),
		new /datum/point_redemption_item("Defense Equipment - Kinetic Dagger",	/obj/item/kinetic_crusher/dagger,				1200),
		new /datum/point_redemption_item("Defense Equipment - Kinetic Gauntlets",	/obj/item/kinetic_gauntlets,				2000),
		new /datum/point_redemption_item("Bar Shelter Capsule",		/obj/item/survivalcapsule/luxurybar,							10000)
	)
