static_files:
  - name: config
    populate: true
  - name: data
  - name: tmp
linux_scripts:
  PreCompile.sh: tools/tgs4_scripts/PreCompile.sh
windows_scripts:
  PreCompile.bat: tools/tgs4_scripts/PreCompile.bat
