/**
 * left behind by teleports / generated by portals
 */
/datum/bluespace_wake
	/// source turf
	var/turf/source
	/// destination turf
	var/turf/destination
	/// is still active (open portals)
	var/still_active = FALSE
	/// bidirectional in nature (but not necessarily usage)
	var/was_bidirectional = FALSE

	#warn impl
