//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2023 Citadel Station developers.          *//

/obj/machinery/teleporter
	#warn sprite

	default_deconstruct = TOOL_CROWBAR
	default_unanchor = TOOL_WRENCH
	default_panel = TOOL_SCREWDRIVER

	/// linked controller
	var/obj/machinery/teleporter_controller/controller
	/// autolink controller id - normal link checks are still done
	var/controller_autolink_id

	/// name tag - autogenerated if not specified
	var/label

/obj/machinery/teleporter/Initialize(mapload)
	#warn impl + autogen label
	return ..()

/obj/machinery/teleporter/Destroy()
	unlink_controller()
	return ..()

/obj/machinery/teleporter/proc/link_controller(obj/machinery/teleporter_controller/controller)
	#warn impl

/obj/machinery/teleporter/proc/unlink_controller()
	#warn impl

/obj/machinery/teleporter/ui_data(mob/user, datum/tgui/ui, datum/ui_state/state)
	. = ..()
	.["linkedController"] = !isnull(controller)

/obj/machinery/teleporter/ui_static_data(mob/user, datum/tgui/ui, datum/ui_state/state)
	. = ..()
	.["label"] = label

/obj/machinery/teleporter/proc/set_label(label)
	src.label = label
	push_ui_data(data = list("label" = label))
	#warn update controllers?

#warn common .tsx file
#warn controller should atleast show its id/whatnot
