//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2025 Citadel Station Developers           *//

/datum/player_ban
	var/ban_id
	var/match_player_id
	var/match_ckey
	var/match_ip
	var/match_computer_id
	var/type_class
	var/type_id
	/// plaintext generated by subsystem
	/// * not always filled out; if looking up metadata
	var/list/edit_log
