//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2024 Citadel Station Developers           *//

/**
 * Basic emotes that just emit a simple message or something.
 *
 * * This is in reality just a generic emote subtype that handles most cases.
 * * 'arbitrary' will be a list of key-values, with EMOTE_PARAMETER_KEY_*.
 * * parameters are a list of strings; you can do strings with spaces with "string here". \" will escape doublequotes, \\ will escape a \
 * * named parameters are not yet supported. it's too expensive to process these.
 * * you are allowed one custom parameter in addition to default parameters generated by this type (like 'target').
 * * the custom parameter will be under EMOTE_PARAMETER_KEY_CUSTOM.
 */
/datum/emote/standard/basic
	abstract_type = /datum/emote/standard/basic

	//* Feedback *//

	/// outgoing saycode type flags
	var/feedback_saycode_type = SAYCODE_TYPE_AUTO

	/**
	 * Override order as follows:
	 *
	 * 1. Miming, if miming
	 * 2. Muzzled, if muzzled
	 * 3. Targeted, if there is a target
	 * 4. Default
	 */

	/// if existing, and we're miming, we immediately switch saycode mode to visible if we're on auto
	///
	/// * %USER% is replaced with the user.
	/// * %TARGET% is replaced with a target, if one exists
	/// * If the hearer is blind / cannot see someone, it's replaced with 'someone' instead of the user / target
	/// * If the replacement is at the start of the string, it'll be capitalized as needed.
	var/feedback_special_miming

	/// if existing, and we're muzzled, we immediately switch to this
	///
	/// * %USER% is replaced with the user.
	/// * %TARGET% is replaced with a target, if one exists
	/// * If the hearer is blind / cannot see someone, it's replaced with 'someone' instead of the user / target
	/// * If the replacement is at the start of the string, it'll be capitalized as needed.
	var/feedback_special_muzzled
	/// audible descriptor for muzzled; if empty string, we render no message. if null, we default to muzzled.
	///
	/// * %USER% is replaced with the user.
	/// * %TARGET% is replaced with a target, if one exists
	/// * If the hearer is blind / cannot see someone, it's replaced with 'someone' instead of the user / target
	/// * If the replacement is at the start of the string, it'll be capitalized as needed.
	var/feedback_special_muzzled_audible

	/// if existing, we jump immediately if there is a target set to this,
	/// replacing %USER% with the user and %TARGET% with the target
	///
	/// * If heard, audible has %USER% replaced with "someone" if the viewer is blind.
	/// * If heard, audible has %TARGET% replaced with "someone" if the viewer is blind.
	/// * If the replacement is at the start of the string, it'll be capitalized as needed.
	/// * Overridden by both miming and muzzled overrides, if they exist.
	var/feedback_special_targeted
	/// Audible descriptor override; other rules still apply for targeted replace
	///
	/// * requires the normal message to be set for this to be invoked.
	var/feedback_special_targeted_audible

	/// the default feedback string
	///
	/// * If heard, audible has %USER% replaced with "someone" if the viewer is blind.
	/// * If the replacement is at the start of the string, it'll be capitalized as needed.
	/// * Overridden by targeted, miming, and muzzled overrides, if they exist.
	var/feedback_default
	/// the default audible feedback string
	///
	/// * If heard, audible has %USER% replaced with "someone" if the viewer is blind.
	/// * If the replacement is at the start of the string, it'll be capitalized as needed.
	/// * Overridden by targeted, miming, and muzzled overrides, if they exist.
	var/feedback_default_audible

	//* Parameter *//

	/// your custom parameter help string
	var/parameter_custom_description

	//* Targeting *//

	/// Allows targeting?
	var/target_allowed = FALSE
	/// requires a target?
	var/target_required = FALSE
	/// maximum distance target can be from us
	var/max_distance = 7

/datum/emote/standard/basic/New()
	if(isnull(parameter_description))
		parameter_description = generate_parameter_description()
	else
		stack_trace("[NAMEOF(src, parameter_description)] was set, but it should be autogenerated!")
	..()

/datum/emote/standard/basic/proc/generate_parameter_description()
	#warn impl

/datum/emote/standard/basic/process_parameters(datum/event_args/actor/actor, parameter_string)
	#warn impl

/datum/emote/standard/basic/try_run_emote(datum/event_args/actor/actor, list/arbitrary)
	. = ..()
	#warn impl

/datum/emote/standard/basic/run_emote(datum/event_args/actor/actor, list/arbitrary)
	. = ..()
	#warn impl

/**
 * Processes a custom parameter
 */
/datum/emote/standard/basic/proc/process_custom_parameter(datum/event_args/actor/actor, string)
	// default to just spitting the string back out
	return string

#warn impl


