#define JOB_PRIORITY_LOW 1
#define JOB_PRIORITY_MEDIUM 2
#define JOB_PRIORITY_HIGH 3

#define JOB_ALTERNATIVE_GET_RANDOM 0
#define JOB_ALTERNATIVE_BE_ASSISTANT 1
#define JOB_ALTERNATIVE_RETURN_LOBBY 2
