
#define PREFERENCE_LOAD_ORDER_REAL_SPECIES -50
#define PREFERENCE_LOAD_ORDER_DEFAULT 0
#define PREFERENCE_LOAD_ORDER_CHAR_SPECIES 20
#define PREFERENCE_LOAD_ORDER_LORE 50
#define PREFERENCE_LOAD_ORDER_LANGUAGE 60
