/**
 * Standard Spans
 * Sorted alphabetically
 *
 * '_CONST' versions work at compile-time, but potentially carry runtime overhead if used
 * normally.
 */

#define SPAN_ABDUCTOR(STR) ("<span class='abductor'>[STR]</span>")
#define SPAN_ADMIN(STR) ("<span class='admin'>[STR]</span>")
#define SPAN_ADMINHELP(STR) ("<span class='adminhelp'>[STR]</span>")
#define SPAN_ADMINNOTICE(STR) ("<span class='adminnotice'>[STR]</span>")
#define SPAN_ADMINOBSERVEROOC(STR) ("<span class='adminobserverooc'>[STR]</span>")
#define SPAN_ADMINOOC(STR) ("<span class='adminooc'>[STR]</span>")
#define SPAN_ADMINSAY(STR) ("<span class='adminsay'>[STR]</span>")
#define SPAN_AIPRIVRADIO(STR) ("<span class='aiprivradio'>[STR]</span>")
#define SPAN_ALERT(STR) ("<span class='alert'>[STR]</span>")
#define SPAN_ALERTALIEN(STR) ("<span class='alertalien'>[STR]</span>")
#define SPAN_ALERTSYNDIE(STR) ("<span class='alertsyndie'>[STR]</span>")
#define SPAN_ALERTWARNING(STR) ("<span class='alertwarning'>[STR]</span>")

#define SPAN_ALIEN(STR) ("<span class='alien'>[STR]</span>")
#define SPAN_ALIEN_CONST(STR) ("<span class='alien'>" + STR + "</span>")

#define SPAN_ALLOY(STR) ("<span class = 'alloy'>[STR]</span>")
#define SPAN_ALLOYH(STR) ("<span class = 'heavy_alloy'>[STR]</span>")
#define SPAN_ANNOUNCE(STR) ("<span class='announce'>[STR]</span>")
#define SPAN_BIG(STR) ("<span class='big'>[STR]</span>")
#define SPAN_BIGICON(STR) ("<span class='bigicon'>[STR]</span>")
#define SPAN_BINARYSAY(STR) ("<span class='binarysay'>[STR]</span>")
#define SPAN_BLUE(STR) ("<span class='blue'>[STR]</span>")
#define SPAN_BLUETEAMRADIO(STR) ("<span class='blueteamradio'>[STR]</span>")
#define SPAN_BOLD(STR) ("<span class='bold'>[STR]</span>")
#define SPAN_BOLDANNOUNCE(STR) ("<span class='boldannounce'>[STR]</span>")
#define SPAN_BOLDDANGER(STR) ("<span class='bolddanger'>[STR]</span>")
#define SPAN_BOLDNICEGREEN(STR) ("<span class='boldnicegreen'>[STR]</span>")
#define SPAN_BOLDNOTICE(STR) ("<span class='boldnotice'>[STR]</span>")
#define SPAN_BOLDWARNING(STR) ("<span class='boldwarning'>[STR]</span>")
#define SPAN_BRASS(STR) ("<span class = 'brass'>[STR]</span>")
#define SPAN_BRASSH(STR) ("<span class = 'heavy_brass'>[STR]</span>")
#define SPAN_BRASSL(STR) ("<span class = 'large_brass'>[STR]</span>")
#define SPAN_BRASSBIG(STR) ("<span class = 'big_brass'>[STR]</span>")
#define SPAN_CAUTION(STR) ("<span class='caution'>[STR]</span>")
#define SPAN_CENTCOMRADIO(STR) ("<span class='centcomradio'>[STR]</span>")
#define SPAN_CHANGELING(STR) ("<span class='changeling'>[STR]</span>")
#define SPAN_CLOWN(STR) ("<span class='clown'>[STR]</span>")
#define SPAN_COLOSSUS(STR) ("<span class='colossus'>[STR]</span>")
#define SPAN_COMMAND_HEADSET(STR) ("<span class='command_headset'>[STR]</span>")
#define SPAN_COMRADIO(STR) ("<span class='comradio'>[STR]</span>")
#define SPAN_CRITICAL(STR) ("<span class='critical'>[STR]</span>")
#define SPAN_CULT(STR) ("<span class='cult'>[STR]</span>")
#define SPAN_CULTBOLD(STR) ("<span class='cultbold'>[STR]</span>")
#define SPAN_CULTBOLDTALIC(STR) ("<span class='cultboldtalic'>[STR]</span>")
#define SPAN_CULTITALIC(STR) ("<span class='cultitalic'>[STR]</span>")
#define SPAN_CULTLARGE(STR) ("<span class='cultlarge'>[STR]</span>")

#define SPAN_DANGER(STR) ("<span class='danger'>[STR]</span>")
#define SPAN_DANGER_CONST(STR) ("<span class='danger'>" + STR + "</span>")

#define SPAN_DEADSAY(STR) ("<span class='deadsay'>[STR]</span>")
#define SPAN_DEBUG(STR) ("<span class='debug_debug'>[STR]</span>")
#define SPAN_DEBUGERROR(STR) ("<span class='debug_error'>[STR]</span>")
#define SPAN_DEBUGINFO(STR) ("<span class='debug_info'>[STR]</span>")
#define SPAN_DEBUGTRACE(STR) ("<span class='debug_trace'>[STR]</span>")
#define SPAN_DEBUGWARNING(STR) ("<span class='debug_warning'>[STR]</span>")
#define SPAN_DECONVERSION_MESSAGE(STR) ("<span class='deconversion_message'>[STR]</span>")
#define SPAN_DRONE(STR) ("<span class='drone'>[STR]</span>")
#define SPAN_ENGRADIO(STR) ("<span class='engradio'>[STR]</span>")
#define SPAN_EXTREMELYBIG(STR) ("<span class='extremelybig'>[STR]</span>")
#define SPAN_EMOTE(STR) ("<span class='emote'>[STR]</span>")
#define SPAN_EXPRADIO(STR) ("<span class='expradio'>[STR]</span>")
#define SPAN_ENTRADIO(STR) ("<span class='entradio'>[STR]</span>")
#define SPAN_GANGRADIO(STR) ("<span class='gangradio'>[STR]</span>")
#define SPAN_GHOSTALERT(STR) ("<span class='ghostalert'>[STR]</span>")
#define SPAN_GREEN(STR) ("<span class='green'>[STR]</span>")
#define SPAN_GREENANNOUNCE(STR) ("<span class='greenannounce'>[STR]</span>")
#define SPAN_GREENTEAMRADIO(STR) ("<span class='greenteamradio'>[STR]</span>")
#define SPAN_GREENTEXT(STR) ("<span class='greentext'>[STR]</span>")
#define SPAN_GREY(STR) ("<span class='grey'>[STR]</span>")
#define SPAN_HEAR(STR) ("<span class='hear'>[STR]</span>")
#define SPAN_HELPFUL(X) "<span class='helpful'>[X]</span>"
#define SPAN_HIDDEN(STR) ("<span class='hidden'>[STR]</span>")
#define SPAN_HIEROPHANT_WARNING(STR) ("<span class='hierophant_warning'>[STR]</span>")
#define SPAN_HIEROPHANT(STR) ("<span class='hierophant'>[STR]</span>")
#define SPAN_HIGHLIGHT(STR) ("<span class='highlight'>[STR]</span>")
#define SPAN_HIS_GRACE(STR) ("<span class='his_grace'>[STR]</span>")
#define SPAN_HOLOPARASITE(STR) ("<span class='holoparasite'>[STR]</span>")
#define SPAN_HYPNOPHRASE(STR) ("<span class='hypnophrase'>[STR]</span>")
#define SPAN_ICON(STR) ("<span class='icon'>[STR]</span>")
#define SPAN_INATHNEQ(STR) ("<span class = 'inathneq'>[STR]</span>")
#define SPAN_INATHNEQL(STR) ("<span class = 'inathneq_large'>[STR]</span>")
#define SPAN_INFO(STR) ("<span class='info'>[STR]</span>")
#define SPAN_INFOPLAIN(STR) ("<span class='infoplain'>[STR]</span>")

#define SPAN_INTERFACE(STR) ("<span class='interface'>[STR]</span>")
#define SPAN_INTERFACE_CONST(STR) ("<span class='interface'>" + STR + "</span>")

#define SPAN_ITALICS(STR) ("<span class='italics'>" + STR + "</span>")
#define SPAN_LINKIFY(STR) ("<span class='linkify'>[STR]</span>")
#define SPAN_LOOC(STR) ("<span class='looc'>[STR]</span>")
#define SPAN_MEDAL(STR) ("<span class='medal'>[STR]</span>")
#define SPAN_MEDRADIO(STR) ("<span class='medradio'>[STR]</span>")
#define SPAN_MEMO(STR) ("<span class='memo'>[STR]</span>")
#define SPAN_MEMOEDIT(STR) ("<span class='memoedit'>[STR]</span>")
#define SPAN_MIND_CONTROL(STR) ("<span class='mind_control'>[STR]</span>")
#define SPAN_MINORANNOUNCE(STR) ("<span class='minorannounce'>[STR]</span>")
#define SPAN_MONKEY(STR) ("<span class='monkey'>[STR]</span>")
#define SPAN_MONKEYHIVE(STR) ("<span class='monkeyhive'>[STR]</span>")
#define SPAN_MONKEYLEAD(STR) ("<span class='monkeylead'>[STR]</span>")
#define SPAN_NAME(STR) ("<span class='name'>[STR]</span>")
#define SPAN_NARSIE(STR) ("<span class='narsie'>[STR]</span>")
#define SPAN_NARSIESMALL(STR) ("<span class='narsiesmall'>[STR]</span>")
#define SPAN_NEOVGRE(STR) ("<span class = 'neovgre'> [STR]</span>")
#define SPAN_NEOVGREL(STR) ("<span class = 'neovgre_large'> [STR]</span>")
#define SPAN_NEZBERE(STR) ("<span class = 'nezbere'>[STR]</span>")
#define SPAN_NEZBIG(STR) ("<span class = 'nezbere_large'>[STR]</span>")
#define SPAN_NZCRENTR(STR) ("<span class = 'nzcrentr'>[STR]</span>")
#define SPAN_NZCRENTRL(STR) ("<span class = 'nzcrentr_large'>[STR]</span>")
#define SPAN_NICEGREEN(STR) ("<span class='nicegreen'>[STR]</span>")

#define SPAN_NOTICE(STR) ("<span class='notice'>[STR]</span>")
#define SPAN_NOTICE_CONST(STR) ("<span class='notice'>" + STR + "</span>")

#define SPAN_NOTICEALIEN(STR) ("<span class='noticealien'>[STR]</span>")
#define SPAN_OOC(STR) ("<span class='ooc'>[STR]</span>")
#define SPAN_PAPYRUS(STR) ("<span class='papyrus'>[STR]</span>")
#define SPAN_PHOBIA(STR) ("<span class='phobia'>[STR]</span>")
#define SPAN_PREFIX(STR) ("<span class='prefix'>[STR]</span>")
#define SPAN_PURPLE(STR) ("<span class='purple'>[STR]</span>")
#define SPAN_RADIO(STR) ("<span class='radio'>[STR]</span>")
#define SPAN_RATVAR(STR) ("<span class = 'ratvar'> [STR]</span>")
#define SPAN_REALLYBIG(STR) ("<span class='reallybig'>[STR]</span>")
#define SPAN_RED(STR) ("<span class='red'>[STR]</span>")
#define SPAN_REDTEAMRADIO(STR) ("<span class='redteamradio'>[STR]</span>")
#define SPAN_REDTEXT(STR) ("<span class='redtext'>[STR]</span>")
#define SPAN_RESONATE(STR) ("<span class='resonate'>[STR]</span>")
#define SPAN_REVENBIGNOTICE(STR) ("<span class='revenbignotice'>[STR]</span>")
#define SPAN_REVENBOLDNOTICE(STR) ("<span class='revenboldnotice'>[STR]</span>")
#define SPAN_REVENDANGER(STR) ("<span class='revendanger'>[STR]</span>")
#define SPAN_REVENMINOR(STR) ("<span class='revenminor'>[STR]</span>")
#define SPAN_REVENNOTICE(STR) ("<span class='revennotice'>[STR]</span>")
#define SPAN_REVENWARNING(STR) ("<span class='revenwarning'>[STR]</span>")
#define SPAN_ROBOT(STR) ("<span class='robot'>[STR]</span>")
#define SPAN_ROSE(STR) ("<span class='rose'>[STR]</span>")
#define SPAN_SANS(STR) ("<span class='sans'>[STR]</span>")
#define SPAN_SCIRADIO(STR) ("<span class='sciradio'>[STR]</span>")
#define SPAN_SECRADIO(STR) ("<span class='secradio'>[STR]</span>")
#define SPAN_SERVRADIO(STR) ("<span class='servradio'>[STR]</span>")
#define SPAN_SINGING(STR) ("<span class='singing'>[STR]</span>")
#define SPAN_SLIME(STR) ("<span class='slime'>[STR]</span>")
#define SPAN_SMALL(STR) ("<span class='small'>[STR]</span>")
#define SPAN_SMALLNOTICE(STR) ("<span class='smallnotice'>[STR]</span>")
#define SPAN_SMALLNOTICEITAL(STR) ("<span class='smallnoticeital'>[STR]</span>")
#define SPAN_SOGHUN(STR) ("<span class='soghun'>[STR]</span>")
#define SPAN_SPIDER(STR) ("<span class='spider'>[STR]</span>")
#define SPAN_SUICIDE(STR) ("<span class='suicide'>[STR]</span>")
#define SPAN_SUPPRADIO(STR) ("<span class='suppradio'>[STR]</span>")
#define SPAN_SYNDRADIO(STR) ("<span class='syndradio'>[STR]</span>")
#define SPAN_TAPE_RECORDER(STR) ("<span class='tape_recorder'>[STR]</span>")
#define SPAN_TINY(STR) ("<span class='tiny'>[STR]</span>")

#define SPAN_TINYNOTICE(STR) ("<span class='tinynotice'>[STR]</span>")
#define SPAN_TINYNOTICE_CONST(STR) ("<span class='tinynotice'>" + STR + "</span>")

#define SPAN_TINYNOTICEITAL(STR) ("<span class='tinynoticeital'>[STR]</span>")
#define SPAN_UNCONSCIOUS(STR) ("<span class='unconscious'>[STR]</span>")
#define SPAN_USERDANGER(STR) ("<span class='userdanger'>[STR]</span>")
#define SPAN_VOTENOTIFICATION(STR) ("<span class='votenotification'>[STR]</span>")
#define SPAN_WARNING(STR) ("<span class='warning'>[STR]</span>")
#define SPAN_YELL(STR) ("<span class='yell'>[STR]</span>")
#define SPAN_YELLOWTEAMRADIO(STR) ("<span class='yellowteamradio'>[STR]</span>")

/**
 * Spans that use embedded tgui components:
 * Sorted alphabetically
 */

/// Displays a tooltip. Tooltip is text-only, and HTML will be ignored.
/// * SPAN_LINKIFY doesn't work here.
#define SPAN_TOOLTIP(TIP, STR) ("<span data-component=\"Tooltip\" data-content=\"[html_encode(TIP)]\" class=\"tooltip\">[STR]</span>")
/// Displays a tooltip. Accepts HTML. For the love of all that is holy, ensure input is trusted.
/// * SPAN_LINKIFY doesn't work here.
#define SPAN_TOOLTIP_DANGEROUS_HTML(TIP, STR) ("<span data-component=\"TooltipHTML\" data-html=\"[html_encode(TIP)]\" class=\"tooltip\">[STR]</span>")

/**
 * Special Macros
 * These aren't really spans but we'll call them such just to make shit easier
 */
#define SPAN_BLOCKQUOTE(STR, SPAN_TYPE) ("<blockquote class=[(isnull(SPAN_TYPE) ? "" : SPAN_TYPE)]>[STR]</blockquote>")
