#define BODYPART_NO_INJECT       (1 << 0)
#define BODYPART_NO_HEAL         (1 << 1)
#define BODYPART_NO_SURGERY      (1 << 2)
#define BODYPART_NO_PATCH	     (1 << 3)
#define BODYPART_SILENT_WOUNDS   (1 << 4)
#define BODYPART_NO_INFECTION    (1 << 5)
