// holiday names
#define HOLIDAY_NEW_YEAR 			"New Years's Day"
#define HOLIDAY_SKRELL_ROYALS 		"Vertalliq-Qerr"
#define HOLIDAY_GROUNDHOG 			"Groundhog Day"
#define HOLIDAY_VALENTINES 			"Valentine's Day"
#define HOLIDAY_RANDOM_KINDNESS 	"Random Acts of Kindness Day"
#define HOLIDAY_SKRELL_MOURNING 	"Qixm-tes"
#define HOLIDAY_PI 					"Pi Day"
#define HOLIDAY_EASTER				"Easter"
#define HOLIDAY_ST_PATRICK 			"St. Patrick's Day"
#define HOLIDAY_APRIL_FOOLS			"April Fool's Day"
#define HOLIDAY_EARTH 				"Earth Day"
#define HOLIDAY_WORKERS 			"Interstellar Workers' Day"
#define HOLIDAY_REMEMBRANCE 		"Remembrance Day"
#define HOLIDAY_SKRELL_CELEBRATION 	"Jiql-tes"
#define HOLIDAY_SAPIENT_RIGHTS 		"Sapient Rights Day"
#define HOLIDAY_BLOOD_DONOR 		"Blood Donor Day"
#define HOLIDAY_CIVIL_SERVANTS 		"Civil Servant's Day"
#define HOLIDAY_DOCTORS 			"Doctors' Day"
#define HOLIDAY_FRIENDSHIP 			"Friendship Day"
#define HOLIDAY_VORE 				"Vore Day"
#define HOLIDAY_FORGIVENESS 		"Forgiveness Day"
#define HOLIDAY_SKRELL_DEAD 		"Qill-xamr"
#define HOLIDAY_PIRATE 				"Talk-Like-a-Pirate Day"
#define HOLIDAY_STUPID_QUESTION 	"Stupid-Questions Day"
#define HOLIDAY_BOSS 				"Boss' Day"
#define HOLIDAY_KINDNESS 			"Kindness Day"
#define HOLIDAY_THANKSGIVING 		"Thanksgiving"
#define HOLIDAY_HUMAN_RIGHTS 		"Human-Rights Day"
#define HOLIDAY_SKRELL_LANDING 		"Vertalliq-qixim"
#define HOLIDAY_NEW_YEAR_EVE 		"New Year's Eve"
#define HOLIDAY_FRIDAY_THIRTEEN 	"Friday the 13th"
#define HOLIDAY_CHRISTMAS			"Christmas"
#define HOLIDAY_HALLOWEEN			"Halloween"
