#define DEFAULT_HOLOGRAM_OTHER_ALPHA 230

#define DEFAULT_HOLOGRAM_BODY_ALPHA 100
#define MINIMUM_HOLOGRAM_BODY_ALPHA 50
#define MAXIMUM_HOLOGRAM_BODY_ALPHA 255

#define DEFAULT_HOLOGRAM_CLOTHING_ALPHA 255
#define MINIMUM_HOLOGRAM_CLOTHING_ALPHA 50
#define MAXIMUM_HOLOGRAM_CLOTHING_ALPHA 255

#define DEFAULT_HOLOGRAM_HAIR_ALPHA 255
#define MINIMUM_HOLOGRAM_HAIR_ALPHA 0
#define MAXIMUM_HOLOGRAM_HAIR_ALPHA 255
