//Material "index"
#define MATERIAL_ALLL "ALL"
#define MATERIAL_PRIMARY "PRIMARY"

//Defaults
#define DEFAULT_WALL_MATERIAL_ID MATERIAL_ID_STEEL
#define DEFAULT_TABLE_MATERIAL_ID MATERIAL_ID_PLASTIC

//MATERIAL IDS
#define MATERIAL_ID_ABSTRACT "INVALID_MATERIAL"

//Metals
#define MATERIAL_ID_IRON		"IRON"
#define MATERIAL_ID_GOLD		"GOLD"
#define MATERIAL_ID_SILVER		"SILVER"
#define MATERIAL_ID_TITANIUM	"TITANIUM"
	#define MATERIAL_ID_TITANIUM_HULL		"TITANIUM_HULL"

//Gems
#define MATERIAL_ID_DIAMOND			"DIAMOND"
#define MATERIAL_ID_PHORON			"PHORON"
#define MATERIAL_ID_SUPERMATTER		"SUPERMATTER"

//Wood
#define MATERIAL_ID_WOOD		"WOOD"
	#define MATERIAL_ID_HOLOWOOD	"WOOD_HOLO"
	#define MATERIAL_ID_SIFWOOD		"WOOD_SIF"
#define MATERIAL_ID_LOG			"LOG"
	#define MATERIAL_ID_SIFLOG		"LOG_SIF"

//Alloys
#define MATERIAL_ID_PLASTEEL		"PLASTEEL"
	#define MATERIAL_ID_PLASTEEL_HULL	"PLASTEEL_HULL"
#define MATERIAL_ID_DURASTEEL		"DURASTEEL"
	#define MATERIAL_ID_DURASTEEL_HULL"	"DURASTEEL_HULL"
#define MATERIAL_ID_STEEL		"STEEL"
	#define MATERIAL_ID_STEEL_HULL	"STEEL_HULL"

//Stone
#define MATERIAL_ID_SANDSTONE		"SANDSTONE"
#define MATERIAL_ID_MARBLE			"MARBLE"

//Misc
#define MATERIAL_ID_SNOWBRICK		"SNOWBRICK"

//Cloth
#define MATERIAL_ID_CLOTH_BASIC		"CLOTH"
#define MATERIAL_ID_CLOTH_TEAL		"CLOTH_TEAL"
#define MATERIAL_ID_CLOTH_BLACK		"CLOTH_BLACK"
#define MATERIAL_ID_CLOTH_GREEN		"CLOTH_GREEN"
#define MATERIAL_ID_CLOTH_PURPLE	"CLOTH_PURPLE"
#define MATERIAL_ID_CLOTH_BLUE		"CLOTH_BLUE"
#define MATERIAL_ID_CLOTH_BEIGE		"CLOTH_BEIGE"
#define MATERIAL_ID_CLOTH_LIME		"CLOTH_LIME"

//Cult/Arcane
#define MATERIAL_ID_CULT				"CULT"
#define MATERIAL_ID_CULT_REINFORCEd		"CULT_REINFORCED"

//Alien alloy/adminspawn only
#define MATERIAL_ID_ALIEN_ALLOY			"ALIEN_ALLOY"
#define MATERIAL_ID_ELEVATOR_WALL		"ELEVATORIUM"
#define MATERIAL_ID_DUNGEON_WALL		"DUNGEONIUM"
#define MATERIAL_ID_BEDROCK				"BEDROCK"
#define MATERIAL_ID_ALIEN_STEEL			"ALIEN_STEEL"
