//? Recipe Categories

#define CAT_NONE	""

#define CAT_AMMO	"Ammunition"
#define CAT_BREAD	"Breads"
#define CAT_BURGER	"Burgers"
#define CAT_CAKE	"Cakes"
#define CAT_CLOTHING	"Clothing"
#define CAT_DONUT	"Donuts"
#define CAT_EGG	"Egg-Based Food"
#define CAT_FOOD	"Foods"
#define CAT_FURNITURE "Furniture"
#define CAT_ICE	"Frozen"
#define CAT_MEAT	"Meats"
#define CAT_MELEE	"Melee Weapons"
#define CAT_MEXICAN	"Mexican"
#define CAT_MISC	"Misc"
#define CAT_MISCELLANEOUS	"Miscellaneous"
#define CAT_MISCFOOD	"Misc. Food"
#define CAT_OTHER	"Other"
#define CAT_PARTS	"Weapon Parts"
#define CAT_PASTRY	"Pastries"
#define CAT_PIE	"Pies & Sweets"
#define CAT_PIZZA	"Pizzas"
#define CAT_PRIMAL  "Tribal"
#define CAT_ROBOT	"Robots"
#define CAT_SALAD	"Salads"
#define CAT_SANDWICH	"Sandwiches"
#define CAT_SEAFOOD    "Seafood"
#define CAT_SOUP	"Soups"
#define CAT_SPAGHETTI	"Spaghettis"
#define CAT_TOOL	"Tools & Storage"
#define CAT_WEAPON	"Ranged Weapons"
#define CAT_WEAPONRY	"Weaponry"
