///OnTopic return values
#define PREFERENCES_NOACTION 0
#define PREFERENCES_HANDLED 1
#define PREFERENCES_REFRESH 2
#define PREFERENCES_UPDATE_PREVIEW 4
#define PREFERENCES_REFRESH_UPDATE_PREVIEW (PREFERENCES_REFRESH|PREFERENCES_UPDATE_PREVIEW)
