//Civilian Mecha
/obj/vehicle/sealed/mecha/working/ripley
	description_fluff = "The Armored Power Loader Unit, more commonly referred to as the 'Ripley', is a tried and tested exosuit model. Often described as the workhorse of the Frontier, the Ripley was originally designed for industrial use. The APLU is a second generation improvement of the original PLU. The APLU possesses a fully enclosed cockpit enabling it to work in vacuum. The APLU retains the PLU's rugged design and resilience, and is frequently employed in mining, construction, and cargo transport capacities. Coming in at just under 9'(2.7m) tall, the APLU cockpit is cramped, requiring its pilot to stand upright and move in conjunction with the exosuit."

/obj/vehicle/sealed/mecha/working/hoverpod
	description_fluff = "This small space-capable craft can accomodate one pilot and up to two passengers, depending on its equipment. The Hoverpod's trademark round design and bright white coloration are easily recognizable to spacefarers. The design has been in use for nearly two centuries, and has remained largely consistent. Developed to address short ranged transport of crew and cargo in EVA, the Hoverpod is a niche vehicle. Due to its reduced size and maneuverability, the Hoverpod saw frequent use in situations where a shuttle was deemed too cumbersome. Thanks to their ability to enter airlocks, Hoverpods have acted as a bridge between EVA in space suits and travelling within proper spacecraft. In recent times, however, the Hoverpod has begun to show its age. Newer solutions that address the same niche have begun to come to the forefront. In spite of this, the Hoverpod remains a cheap and reliable favorite across the Frontier."

//Medical Mecha
/obj/vehicle/sealed/mecha/medical/odysseus
	description_fluff = "The dominant medical exosuit on the modern market, the Odysseus is a Vey-Med product designed to incorporate other Vey-Med inventions - like the Sleeper - into a mobile frame. The Odysseus' focus on rescue operations in hazardous environments is augmented with some of the best agility ratings on the civilian market. In spite of its narrow profile, the Odysseus stands slightly taller than the APLU at 9.5'(3m). Capable of operating in vacuum as well as in most adverse weather conditions, the staying power of this mecha speaks volumes for its efficacy."

//Combat Mecha
/obj/vehicle/sealed/mecha/combat/durand
	description_fluff = "The Durand is an aging combat exosuit designed during the Rye-Egress War. Once considered the most durable exosuit ever developed by Humanity, this platform has long since lost that title. In spite of its age, the Durand remains one of the most well built and armored exosuits on the market. Standing at a towering 12'(3.5m), the exosuit boasts depleted uranium armor paneling and a robust electrical harness capable of powering some of the most fearsome weaponry still in use today. Although modern militaries - both Galactic and Corporate - have since moved on to more contemporary models, the Durand continues to see usage with smaller mercenary bands and SysDef elements."

/obj/vehicle/sealed/mecha/combat/gorilla
	description_fluff = "Quadrupedal mech designs are considered excessively rare. This chassis feels more like a vehicle than a proper exosuit as a result. Although specs similar to those found in the Gorilla were patened by Hephaestus over a century ago, the company maintains that it had nothing to do with the production of this machine. When its legs are fully extended the Gorilla stands 20'(6.1m) tall, making it nearly impossible to operate at full speed within the cramped confines of a facility or vessel."

/obj/vehicle/sealed/mecha/combat/gygax
	description_fluff = "The Gygax is a relatively modern exosuit designed for agility and speed without sacrificing durability. These traits have made the Gygax fairly popular among well funded private and corporate security forces. The Gygax features a bespoke actuator assembly that grants the exosuit short-term bursts of unparalleled speed. Consequently, the strain this assembly puts on the exosuit causes damage the unit's structural integrity. In spite of the drawbacks, this feature is frequently utilized by those who require the ability to rapidly respond to conflict. 10'(3m) tall and rotund, the Gygax's cockpit is fully enclosed and protected by the design's diamond-weave armor plating."

/obj/vehicle/sealed/mecha/combat/gygax/dark
	description_fluff = "This variant of the standard Gygax is colloquially referred to as the 'Dark Gygax', on account of the exotic materials used in its construction. The standard Gygax's diamond-weave armor system is augmented with depleted morphium, lending it a darker and marginally more sinister hue. Simultaneously, this upgrade grants the Dark Gygax considerably more resilience without sacrificing the standard model's agility or speed. Due to the gross expenditure required to fabricate a Dark Gygax's armor plating, these platforms are exceedingly rare. Most security forces are content with the protection and utility of the standard Gygax, making this upgrade appear unnecessary. However, the Dark Gygax is often sought out by high-tier asset protection teams and paramilitary outfits."

/obj/vehicle/sealed/mecha/combat/honker
	description_fluff = "Utilized with shocking effectiveness during the Prank War of 2476, the H.O.N.K. mech was commissioned by former Honktifex Maximus Pierrot LXIX. Utilizing advanced technology for its time, these mecha were constructed with the extremely rare alloy Vaudium. Initially viewed by external observers as a simple curiosity, the H.O.N.K. mech's ability to inflict widespread 'hilarity' was not realized until the design was made public some decades later. After less than two years on the open market, harsh sanctions and bans on production were levied across at least thirty six Galactic sectors. In spite of this production moratorium, experts in Robotics may sometimes ignore the warnings and fabricate these suits when asked. This is generally considered to be a poor decision. This plodding mecha comes in at 10'(3m) in height, and features a curiously barrel shaped body that provides supreme stability when firing its weaponry. There is some dispute regarding exactly what H.O.N.K. stands for. The most likely suggestion is generallly accepted to be: 'Hilariously Overpowered Noise Kreator'."

/obj/vehicle/sealed/mecha/combat/honker/cluwne
	description_fluff = "As the unending battle over Vaudium continues raging to this day, it should come as no surprise that both Clowns and Mimes continue to iterate on their unique forms of military technology. The C.L.U.W.N.E. is the successor to the H.O.N.K. mech. Utilizing similar design philosophy and based off of the same chassis, the C.L.U.W.N.E. is significantly more armored and durable, addressing several vulnerabilities in the original H.O.N.K. design. Demonstrably effective, these mecha are frequently deployed to the front lines of the conflict.  Rarely they are even dispatched off-planet to support Clown Commando teams. Due to the immense amount of Vaudium required to fabricate a single C.L.U.W.N.E. mech, their mass production remains untenable. Even if it were, Clown Planet guards the mech's schematics jealously. It is currently assumed that the mecha's designation stands for 'Combative Laughter Unit With New Equipment', though this theory is widely disputed."

/obj/vehicle/sealed/mecha/combat/marauder
	description_fluff = "Developed by Nanotrasen, the Marauder is the modern descendant of the Durand. Stronger, faster, and more resilient, the Marauder has fully supplanted its predecessor. Deployed by Nanotrasen to the fiercest conflict zones during the Phoron War, Marauders quickly gained a reputation for brutal efficiency. Marauders are fielded by the megacorporation to hot zones across the Frontier to this day. Thanks to its status as a military grade weapons platform and its highly proprietary equipment, the Marauder is generally unavailable to civilians - including low-level Nanotrasen duty stations and allied corporations. Standing at 12'(3.5m) tall, the Marauder cockpit is complex and spacious enough to grant the pilot a full range of movement within its spherical shell."

/obj/vehicle/sealed/mecha/combat/marauder/seraph
	description_fluff = "Essentially a Marauder with minor imrprovements, the Seraph combat exosuit is a slight upgrade to its predecessor. Due to the relatively small impact of these changes, the Seraph has not made the Marauder obsolete. Instead Seraph units are generally issued to Nanotrasen paramilitary commanders, where they fill a specialized communications role courtesy of their next-generation communications and electronic warfare suites. Due to the tactical nature of the Seraph's battlefield role, the exosuit is not expected to see combat frequently. In spite of this, the Seraph still fields a combat loadout that enables it to protect itself if attacked unexpectedly."

/obj/vehicle/sealed/mecha/combat/marauder/mauler
	description_fluff = "In spite of their technological advancement and heavily restricted deployments, Nanotrasen Marauders may sometimes be stolen, salvaged, or illictly purchased from corrupt company officials. These repurposed models are designated Maulers - after the first line produced by the Syndicate during the Phoron War. Functionally identical in terms of armor and armament, Maulers are considerably more rare than the already scarce Marauder, and are considered a black market collectable on par with stolen art."

/obj/vehicle/sealed/mecha/combat/phazon
	description_fluff = "The Phazon exosuit is the result of a heavily classified Nanotrasen research initiative. Designed to serve as a reconnaissance, infiltration, and flanking mecha, the Phazon possesses an array of complex and expensive phasing and cloaking systems which allow it to change its matter state and move through solid materials. Although initial field tests were positive, the raw cost of manufacturing the Phazon made mass production untenable. Of the few suits deployed during the Phoron War, none are known to have fallen into enemy hands. In spite of this, corporate espionage has lead to various parts and components becoming available on the black market. The actual circuitry and chips necessary to construct the Phazon, however, remain closely guarded corporate secrets. The exosuit's hover capabilities cause it to float roughly a foot off of the ground. Due to this, although the Janus itself comes in at a moderate 9'(2.7m) in height, it effectively takes up 10' to 11'(3m-3.4m) of space when in operation."

/obj/vehicle/sealed/mecha/combat/phazon/janus
	description_fluff = "An incredibly high-tech exosuit constructed out of salvaged alien components fused with cutting-edge modern technology. This machine is theoretically capable of sublight travel. However, due to the vaguely anomalous nature of its miniaturized, supermatter-fueled Toroidal Bluespace Drive, it is uncertain how this ability manifests."

/obj/vehicle/sealed/mecha/combat/reticent
	description_fluff = "During the Melancholy Occupation of 2476 - callously referred to by their opposition as the 'Prank War' - the people of Le Rien realized the rapidly widening gulf between their technological advancements and Columbina's. Aiming to prevent another such tragedy from happening again, extensive research was conducted on the H.O.N.K. mecha deployed by the Clowns. Although Silencium bears less technological utility, scientists were able to employ its own unique properties in the Reticent's design. An agile mecha plated in a sturdy layer of Silencium, the Reticent was able to move silently through corridors its bulkier opponent could not. Able to close distance with the more range biased H.O.N.K. mecha, Reticent units deployed to occupied zones quickly cleared out mechanized garrisons. Although formidable, the Reticent suffers from a weak chassis - a byproduct of its maneuverability - and is easily disabled once its dense mineral armor is shattered. Its 11'(3.4m) oblong body is designed to move at a forward tilt, assisting the exosuit in rapidly gaining momentum."

/obj/vehicle/sealed/mecha/combat/reticence
	description_fluff = "After fully repelling the Columbinan occupiers in 2503, Le Rien began to construct powerful defensive lines along their borders. Decades of fighting had provided researchers with plenty of insight into the faults and merits of the Reticent design. Although intent on keeping the model in service, the Silent Council decreed that a new mech platform would need to be developed to bolster their static defensive line. The Reticent was far too fragile for border defense. Returning to more traditional mecha design doctrine, the Reticence is larger, heavier, and more armored than its predecessor. A 10'(3m) tall hulk, the Reticence trades in the Reticent's blinding speed for a more powerful shielding system and significant improvements in Silencium armor placement. The Reticence is still able to close the gap and deliver close-range punishment to any who dare violate Le Rien's borders."

/obj/vehicle/sealed/mecha/combat/quasimodo
	description_fluff = "Created near the end of Nanotrasen’s war with the Syndicate, right before they collapsed, the Quasimodo was designed in collaboration with Hephaestus Industries and Nanotrasen as a response to the growing threat of Cybersun Industries mechs such as the Mauler. This massive mech and its shoulder mounted, weapon mount was made to carry Anti Tank/Anti Building armament, generally too large to fit on any smaller mech. Although it was never used, due to the Syndicate disbanding right before it saw the light, before being promptly shelved. But, the project was picked back up due to consistent requests from SDF members for something larger to deal with the ever growing threats from mercenary companies and pirates getting their hands on their own mechs. But of course, only if they had the money for it. The Quasimodo stands at 36’(11m) tall, its cockpit windows made with phoron reinforced glass, and its hull made with many, many layers of durasteel. Usually paired with the Quasimodo is the Hag-30, 155mm, Anti Tank Cannon, due to the fact it’s usually built with it permanently fixed, but other models do exist that have other weapons. As expected, this mech is designed with ground based, open combat in mind."
