//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2023 Citadel Station developers.          *//

/obj/item/bluespace_slipstream
	name = "bluespace slipstream grapple"
	desc = "A device capable of latching onto bluespace wakes generated by teleportation. It is capable of generating new portals, or re-opening old portals."

#warn uh
