/obj/item/bluespace_slipstream
	name = "bluespace slipstream grapple"
	desc = "A device capable of latching onto bluespace wakes generated by teleportation. It is capable of generating new portals, or re-opening old portals."

