//* This file is explicitly licensed under the MIT license. *//
//* Copyright (c) 2024 Citadel Station Developers           *//

// todo: while this is all valid code, this file is commented out because the current weapon racking/pumping/chamber charging system is not good enough to support this.

/**
 * * Uses restricted NT-protomag antimaterial caliber.
 * * Single-shot.
 * * Extremely powerful. Non-acquirable by most means.
 * * Synchronous Slide Charging is inbuilt and non-replaceable.
 */
/obj/item/gun/projectile/ballistic/magnetic/nt_protomag/srp
	name = "anti-materiel rifle"
	desc = "A Hephaestus Industries \"Boltcaster\" Anti-Materiel rifle. Fires ferromagnetic slugs using a bank of internal supercapacitors."
	description_fluff = {"
		A monstrously powerful rifle made during the peak of the Phoron War, the Hephaestus Industries
		\"Boltcaster\" anti-materiel rifle was made to counter the development of personal exosuits as well as the
		looming proliferation of heavy combat synthetics. As potent as it is unwieldy, the weight of this rifle
		makes it impractical to carry unaided, while the recoil generated by the acceleration of the ferromagnetic armatures
		is enough to fracture collarbones and dent most synthetic's chassis - restricting its
		use to operators in armored rigsuits and combat androids sturdy enough to withstand it. The line was discontinued
		after the War, with few surviving prototypes able to be found here and there around the Frontier.
		While technically developed in part with the 'Nanotrasen Protomag' series of prototype mag-charged
		weapons, this rifle was ultimately not adopted by Nanotrasen due to the development of
		pulse weapons, given their similar armor penetration despite having a fraction
		of the recoil.
	"}

#warn impl all
