//! Material Defines
#define MAT_ALGAE          /datum/material/solid/algae
#define MAT_BANANIUM       /datum/material/solid/metal/bananium
#define MAT_BRONZE         /datum/material/solid/metal/bronze
#define MAT_CARBON         /datum/material/solid/carbon
#define MAT_CHITIN         /datum/material/solid/skin/insect
#define MAT_COPPER         /datum/material/solid/metal/copper
#define MAT_DIAMOND        /datum/material/solid/gemstone/diamond
#define MAT_DURASTEEL      /datum/material/solid/metal/durasteel
#define MAT_DURASTEELHULL  /datum/material/solid/metal/durasteel/hull
#define MAT_GLASS          /datum/material/solid/glass
#define MAT_GLASS_BS       /datum/material/solid/glass/borosilicate
#define MAT_GOLD           /datum/material/solid/metal/gold
#define MAT_HARDLOG        /datum/material/solid/wood/log/hardwood
#define MAT_HARDWOOD       /datum/material/solid/wood/hardwood
#define MAT_HEMATITE       /datum/material/solid/hematite
#define MAT_IRON           /datum/material/solid/metal/iron
#define MAT_LEAD           /datum/material/solid/metal/lead
#define MAT_LEATHER        /datum/material/solid/leather
#define MAT_LOG            /datum/material/solid/wood/log
#define MAT_MARBLE         /datum/material/solid/stone/marble
#define MAT_METALHYDROGEN  /datum/material/solid/metallic_hydrogen
#define MAT_MORPHIUM       /datum/material/solid/metal/morphium
#define MAT_MORPHIUMHULL   /datum/material/solid/metal/morphium/hull
#define MAT_OSMIUM         /datum/material/solid/metal/osmium
#define MAT_PHORON         /datum/material/solid/phoron
#define MAT_PLASTEEL       /datum/material/solid/metal/plasteel
#define MAT_PLASTEELHULL   /datum/material/solid/metal/plasteel/hull
#define MAT_PLASTIC        /datum/material/solid/plastic
#define MAT_PLATINUM       /datum/material/solid/metal/platinum
#define MAT_RESIN          /datum/material/solid/resin
#define MAT_RESIN_COMPOUND /datum/material/solid/resin/hybrid
#define MAT_SANDSTONE      /datum/material/solid/stone/sandstone
#define MAT_SIFLOG         /datum/material/solid/wood/log/sif
#define MAT_SIFWOOD        /datum/material/solid/wood/sif
#define MAT_SILENCIUM      /datum/material/solid/stone/silencium
#define MAT_SILVER         /datum/material/solid/metal/silver
#define MAT_SNOW           /datum/material/solid/snow
#define MAT_SNOW_PACKED    /datum/material/solid/snow/brick
#define MAT_STEEL          /datum/material/solid/metal/steel
#define MAT_STEELHULL      /datum/material/solid/metal/steel/hull
#define MAT_SUPERMATTER    /datum/material/solid/super_matter
#define MAT_TITANIUM       /datum/material/solid/metal/titanium
#define MAT_TITANIUMHULL   /datum/material/solid/metal/titanium/hull
#define MAT_URANIUM        /datum/material/solid/metal/uranium
#define MAT_VALHOLLIDE     /datum/material/solid/metal/valhollide
#define MAT_VERDANTIUM     /datum/material/solid/metal/verdantium
#define MAT_WOOD           /datum/material/solid/wood

#define SHARD_SHARD        "shard"
#define SHARD_SHRAPNEL     "shrapnel"
#define SHARD_STONE_PIECE  "piece"
#define SHARD_SPLINTER     "splinters"
#define SHARD_NONE         ""
