#warn impl

#define CARRY_WEIGHT_BASELINE 0

//* Tools

#define CARRY_WEIGHT_HYBRID_TOOLS 1

//* Armor

//* Weapons

#define CARRY_WEIGHT_GUN_LIGHT 3
#define CARRY_WEIGHT_GUN_NORMAL 5
#define CARRY_WEIGHT_GUN_LARGE 7.5
#define CARRY_WEIGHT_GUN_BULKY 10
#define CARRY_WEIGHT_GUN_UNREASONABLE 15
#define CARRY_WEIGHT_GUN_RIDICULOUS 30
#define CARRY_WEIGHT_GUN_VEHICLE 60

//* Spacesuits / RIGs

//* Antags

#define CARRY_WEIGHT_TECHNOMANCER_BULKY_CORE 10
