//? Carry weight defines

#define CARRY_WEIGHT_BASELINE 0

//* Tools

#define CARRY_WEIGHT_HYBRID_TOOLS 1

//* Armor

#define CARRY_WEIGHT_ARMOR_LIGHT 5

#define CARRY_WEIGHT_ARMOR_PLATE_ARMOR 20
#define CARRY_WEIGHT_ARMOR_CHAINMAIL_ARMOR 15

#define CARRY_WEIGHT_ARMOR_BIORADSUIT 10
#define CARRY_WEIGHT_ARMOR_FIRESUIT 10

//* Weapons

#define CARRY_WEIGHT_GUN_LIGHT 3
#define CARRY_WEIGHT_GUN_NORMAL 5
#define CARRY_WEIGHT_GUN_LARGE 7.5
#define CARRY_WEIGHT_GUN_BULKY 10
#define CARRY_WEIGHT_GUN_UNREASONABLE 15
#define CARRY_WEIGHT_GUN_RIDICULOUS 30
#define CARRY_WEIGHT_GUN_VEHICLE 60

//* Spacesuits / RIGs

#define CARRY_WEIGHT_LEGACY_RIG_TECHNICIAN 10
#define CARRY_WEIGHT_LEGACY_RIG_PARAMEDIC 10
#define CARRY_WEIGHT_LEGACY_RIG_COMBAT 15
#define CARRY_WEIGHT_LEGACY_RIG_MILITARY 20

//* Antags

#define CARRY_WEIGHT_CHANGELING_ARMOR 20
#define CARRY_WEIGHT_CULT_VOIDSUIT_HELMET 5
#define CARRY_WEIGHT_CULT_VOIDSUIT 20
#define CARRY_WEIGHT_TECHNOMANCER_BULKY_CORE 10

//* Storage

#define CARRY_WEIGHT_STORAGE_DUFFLEBAG 15
