/datum/asset/spritesheet/simple/pills
	name = "pills"
	assets = list(
		"pill1"  = 'icons/runtime/assets/medical/pills/pill1.png',
		"pill2"  = 'icons/runtime/assets/medical/pills/pill2.png',
		"pill3"  = 'icons/runtime/assets/medical/pills/pill3.png',
		"pill4"  = 'icons/runtime/assets/medical/pills/pill4.png',
		"pill5"  = 'icons/runtime/assets/medical/pills/pill5.png',
		"pill6"  = 'icons/runtime/assets/medical/pills/pill6.png',
		"pill7"  = 'icons/runtime/assets/medical/pills/pill7.png',
		"pill8"  = 'icons/runtime/assets/medical/pills/pill8.png',
		"pill9"  = 'icons/runtime/assets/medical/pills/pill9.png',
		"pill10" = 'icons/runtime/assets/medical/pills/pill10.png',
		"pill11" = 'icons/runtime/assets/medical/pills/pill11.png',
		"pill12" = 'icons/runtime/assets/medical/pills/pill12.png',
		"pill13" = 'icons/runtime/assets/medical/pills/pill13.png',
		"pill14" = 'icons/runtime/assets/medical/pills/pill14.png',
		"pill15" = 'icons/runtime/assets/medical/pills/pill15.png',
		"pill16" = 'icons/runtime/assets/medical/pills/pill16.png',
		"pill17" = 'icons/runtime/assets/medical/pills/pill17.png',
		"pill18" = 'icons/runtime/assets/medical/pills/pill18.png',
		"pill19" = 'icons/runtime/assets/medical/pills/pill19.png',
		"pill20" = 'icons/runtime/assets/medical/pills/pill20.png',
		"pill21" = 'icons/runtime/assets/medical/pills/pill21.png',
		"pill22" = 'icons/runtime/assets/medical/pills/pill22.png',
	)
