/**
 * pictures
 *
 * pictures are no longer kept in memory
 * instead they're written to a special data directory,
 * saved as .png and a .json.
 *
 * a (not recommended) fallback mode does exist for servers
 * without web services. persistence will be entirely disabled in that case.
 */
/datum/picture
	//!# Data
	/// md5 - this is our GUID
	var/md5
	/// taken this round
	var/made_this_round = FALSE
	/// icon file if loaded into memory
	var/icon/loaded
	/// thumbnail icon - cached
	var/icon/thumbnail

	//!# Metadata
	/// name - by user
	var/metadata_name
	/// desc - by user, used as caption
	var/metadata_caption
	/// autogenerated mob descriptions/poses
	var/metadata_text_description
	/// stamps, if any
	var/list/metadata_stamps
	/// scribbled on the back...
	var/metadata_scribbles


