### TOML CONFIGURATION SYSTEM
#
# Adapted from paradise station
#
# # denotes a comment
# [section] to mark a section
# otherwise, just list values.
#
###

##########################################################

[photography]

#

