//? rig zones

#define RIG_ZONE_HEAD (1<<0)
#define RIG_ZONE_CHEST (1<<1)
#define RIG_ZONE_LEFT_ARM (1<<2)
#define RIG_ZONE_RIGHT_ARM (1<<3)
#define RIG_ZONE_LEFT_LEG (1<<4)
#define RIG_ZONE_RIGHT_LEG (1<<5)
#define RIG_ZONE_CONTROLLER (1<<6)

DEFINE_BITFIELD(rig_zones, list(
	BITFIELD(RIG_ZONE_HEAD),
	BITFIELD(RIG_ZONE_CHEST),
	BITFIELD(RIG_ZONE_LEFT_ARM),
	BITFIELD(RIG_ZONE_RIGHT_ARM),
	BITFIELD(RIG_ZONE_LEFT_LEG),
	BITFIELD(RIG_ZONE_RIGHT_LEG),
	BITFIELD(RIG_ZONE_CONTROLLER),
))
