
#define RIG_ZONE_CHEST "chest"
#define RIG_ZONE_HEAD "head"
#define RIG_ZONE_LEFT_ARM "left_arm"
#define RIG_ZONE_RIGHT_ARM "right_arm"
#define RIG_ZONE_LEFT_LEG "left_leg"
#define RIG_ZONE_RIGHT_LEG "right_leg"

#define RIG_ZONES_ALL list( \
	RIG_ZONE_CHEST, \
	RIG_ZONE_HEAD, \
	RIG_ZONE_LEFT_ARM, \
	RIG_ZONE_RIGHT_ARM, \
	RIG_ZONE_LEFT_LEG, \
	RIG_ZONE_RIGHT_LEG, \
)


#define RIG_ZONE_BIT_CHEST (1<<0)
#define RIG_ZONE_BIT_HEAD (1<<1)
#define RIG_ZONE_BIT_LEFT_ARM (1<<2)
#define RIG_ZONE_BIT_RIGHT_ARM (1<<3)
#define RIG_ZONE_BIT_LEFT_LEG (1<<4)
#define RIG_ZONE_BIT_RIGHT_LEG (1<<5)

#define RIG_ZONE_BIT_LEGS (RIG_ZONE_BIT_LEFT_LEG | RIG_ZONE_BIT_RIGHT_LEG)
#define RIG_ZONE_BIT_ARMS (RIG_ZONE_BIT_LEFT_ARM | RIG_ZONE_BIT_RIGHT_ARM)
#define RIG_ZONE_BIT_ALL (ALL)

GLOBAL_REAL_LIST(rig_zones) = RIG_ZONES_ALL
GLOBAL_REAL_LIST(rig_zone_to_bit) = list(
	RIG_ZONE_CHEST = RIG_ZONE_BIT_CHEST,
	RIG_ZONE_HEAD = RIG_ZONE_BIT_HEAD,
	RIG_ZONE_LEFT_ARM = RIG_ZONE_BIT_LEFT_ARM,
	RIG_ZONE_RIGHT_ARM = RIG_ZONE_BIT_RIGHT_ARM,
	RIG_ZONE_LEFT_LEG = RIG_ZONE_BIT_LEFT_LEG,
	RIG_ZONE_RIGHT_LEG = RIG_ZONE_BIT_RIGHT_LEG,
)

DEFINE_BITFIELD_NEW(rig_zone_flags, list(

), list(
	BITFIELD_NEW("Chest", RIG_ZONE_BIT_CHEST),
	BITFIELD_NEW("Head", RIG_ZONE_BIT_HEAD),
	BITFIELD_NEW("Left Arm", RIG_ZONE_BIT_LEFT_ARM),
	BITFIELD_NEW("Right Arm", RIG_ZONE_BIT_RIGHT_ARM),
	BITFIELD_NEW("Left Leg", RIG_ZONE_BIT_LEFT_LEG),
	BITFIELD_NEW("Right Leg", RIG_ZONE_BIT_RIGHT_LEG),
))
