/*****************************
 * Points vendor for engineers
 * Points are aquired via crypto miners.
 *****************************/

/obj/machinery/mineral/equipment_vendor/engineering
    name = "Engineering Equipment Vendor"
    desc = "An equipment vendor for engineers, point generated by the crypto miners can be spend here."
    //icon = 'icons/obj/machines/mining_machines.dmi'
	//icon_state = "mining"
    //circuit = /obj/item/circuitboard/engineering_equip
    prize_list = list(
        //Mining vendor steals
        new /datum/data/mining_equipment("Whiskey",						    /obj/item/reagent_containers/food/drinks/bottle/whiskey,		13),
		new /datum/data/mining_equipment("Absinthe",					    /obj/item/reagent_containers/food/drinks/bottle/absinthe,	    13),
		new /datum/data/mining_equipment("Special Blend Whiskey",		    /obj/item/reagent_containers/food/drinks/bottle/specialwhiskey,	25),
		new /datum/data/mining_equipment("Random Booze",			        /obj/random/alcohol,		                                    13),
		new /datum/data/mining_equipment("Cigar",						    /obj/item/clothing/mask/smokable/cigarette/cigar/havana,        15),
		new /datum/data/mining_equipment("Soap",						    /obj/item/soap/nanotrasen,									    20),
		new /datum/data/mining_equipment("Laser Pointer",				    /obj/item/laser_pointer,										90),
		new /datum/data/mining_equipment("Geiger Counter",				    /obj/item/geiger,											    75),
		new /datum/data/mining_equipment("Plush Toy",					    /obj/random/plushie,											30),
		new /datum/data/mining_equipment("GPS Device",					    /obj/item/gps/engineering,									    10),
		new /datum/data/mining_equipment("50 Point Transfer Card",		    /obj/item/card/mining_point_card/engineering,				    50),
		new /datum/data/mining_equipment("Umbrella",					    /obj/item/melee/umbrella/random,								20),
		new /datum/data/mining_equipment("Space Cash",					    /obj/item/spacecash/c100,									    100),
		new /datum/data/mining_equipment("Hardsuit - Control Module",       /obj/item/rig/industrial,									    200),
		new /datum/data/mining_equipment("Hardsuit - Plasma Cutter",	    /obj/item/rig_module/device/plasmacutter,						100),
		new /datum/data/mining_equipment("Hardsuit - Maneuvering Jets",	    /obj/item/rig_module/maneuvering_jets,							125),
		new /datum/data/mining_equipment("Hardsuit - Intelligence Storage",	/obj/item/rig_module/ai_container,								250),
		new /datum/data/mining_equipment("Hardsuit - Smoke Bomb Deployer",	/obj/item/rig_module/grenade_launcher/smoke,					200),
		new /datum/data/mining_equipment("Injector (L) - Glucose",          /obj/item/reagent_containers/hypospray/autoinjector/biginjector/glucose,	50),
		new /datum/data/mining_equipment("Injector (L) - Panacea",          /obj/item/reagent_containers/hypospray/autoinjector/biginjector/purity,	50),
		new /datum/data/mining_equipment("Injector (L) - Trauma",           /obj/item/reagent_containers/hypospray/autoinjector/biginjector/brute,	50),
		new /datum/data/mining_equipment("Nanopaste Tube",				    /obj/item/stack/nanopaste,										100),
		//Mining vendor steals - Ends
        //Power tools like the CE gets, if kev comes crying: https://cdn.discordapp.com/attachments/296237931587305472/956517623519141908/unknown.png
        new /datum/data/mining_equipment("Power Tool - Hand Drill",                     /obj/item/tool/screwdriver/power,                   100),
        new /datum/data/mining_equipment("Power Tool - Jaws of life",                   /obj/item/tool/crowbar/power,                       100),
        new /datum/data/mining_equipment("Power Tool - Experimental Welder",            /obj/item/weldingtool/experimental,                 100),
        new /datum/data/mining_equipment("Power Tool - Upgraded T-Ray Scanner",         /obj/item/t_scanner/upgraded,                       100),
        new /datum/data/mining_equipment("Power Tool - Advanced T-Ray Scanner",         /obj/item/t_scanner/advanced,                       100),
        new /datum/data/mining_equipment("Power Tool - Long Range Atmosphere scanner",  /obj/item/analyzer/longrange,                       100),
        new /datum/data/mining_equipment("Superior Welding Goggles",                    /obj/item/clothing/glasses/welding/superior,        50),
        //Level 1 Stock parts, not really a good deal but doesnt need resources.
        new /datum/data/mining_equipment("Stock Parts - Capacitor",                 /obj/item/stock_parts/capacitor,        20),
        new /datum/data/mining_equipment("Stock Parts - Scanning Module",           /obj/item/stock_parts/scanning_module,  20),
        new /datum/data/mining_equipment("Stock Parts - Micro-Manipulator",         /obj/item/stock_parts/manipulator,      20),
        new /datum/data/mining_equipment("Stock Parts - Micro-Laser",               /obj/item/stock_parts/micro_laser,      20),
        new /datum/data/mining_equipment("Stock Parts - Matter Bin",                /obj/item/stock_parts/matter_bin,       20),
        
        //Level 2 stock parts, to make engineering kinda self sufficent for minor upgrades but the parts are also kinda expansive
        new /datum/data/mining_equipment("Stock Parts - Advanced Capacitor",        /obj/item/stock_parts/capacitor/adv,        200),
        new /datum/data/mining_equipment("Stock Parts - Advanced Scanning Module",  /obj/item/stock_parts/scanning_module/adv,  200),
        new /datum/data/mining_equipment("Stock Parts - Nano-Manipulator",          /obj/item/stock_parts/manipulator/nano,     200),
        new /datum/data/mining_equipment("Stock Parts - High-Power Micro-Laser",    /obj/item/stock_parts/micro_laser/high,     200),
        new /datum/data/mining_equipment("Stock Parts - Advanced Matter Bin",       /obj/item/stock_parts/matter_bin/adv,       200)
    )

/obj/machinery/mineral/equipment_vendor/interact(mob/user)
	user.set_machine(src)

	var/dat
	dat +="<div class='statusDisplay'>"
	if(istype(inserted_id))
		dat += "You have [inserted_id.engineer_points] engineering points collected. <A href='?src=\ref[src];choice=eject'>Eject ID.</A><br>"
	else
		dat += "No ID inserted.  <A href='?src=\ref[src];choice=insert'>Insert ID.</A><br>"
	dat += "</div>"
	dat += "<br><b>Equipment point cost list:</b><BR><table border='0' width='100%'>"
	for(var/datum/data/mining_equipment/prize in prize_list)
		dat += "<tr><td>[prize.equipment_name]</td><td>[prize.cost]</td><td><A href='?src=\ref[src];purchase=\ref[prize]'>Purchase</A></td></tr>"
	dat += "</table>"
	var/datum/browser/popup = new(user, "miningvendor", "Engineering Equipment Vendor", 400, 600)
	popup.set_content(dat)
	popup.open()

/obj/machinery/mineral/equipment_vendor/Topic(href, href_list)
	if(..())
		return 1

	if(href_list["choice"])
		if(istype(inserted_id))
			if(href_list["choice"] == "eject")
				to_chat(usr, "<span class='notice'>You eject the ID from [src]'s card slot.</span>")
				if(ishuman(usr))
					usr.put_in_hands(inserted_id)
					inserted_id = null
				else
					inserted_id.forceMove(get_turf(src))
					inserted_id = null
		else if(href_list["choice"] == "insert")
			var/obj/item/card/id/I = usr.get_active_hand()
			if(istype(I) && !inserted_id && usr.unEquip(I))
				I.forceMove(src)
				inserted_id = I
				interact(usr)
				to_chat(usr, "<span class='notice'>You insert the ID into [src]'s card slot.</span>")
			else
				to_chat(usr, "<span class='warning'>No valid ID.</span>")
				flick(icon_deny, src)

	if(href_list["purchase"])
		if(istype(inserted_id))
			var/datum/data/mining_equipment/prize = locate(href_list["purchase"])
			if (!prize || !(prize in prize_list))
				to_chat(usr, "<span class='warning'>Error: Invalid choice!</span>")
				flick(icon_deny, src)
				return
			if(prize.cost > inserted_id.engineer_points)
				to_chat(usr, "<span class='warning'>Error: Insufficent points for [prize.equipment_name]!</span>")
				flick(icon_deny, src)
			else
				inserted_id.engineer_points -= prize.cost
				to_chat(usr, "<span class='notice'>[src] clanks to life briefly before vending [prize.equipment_name]!</span>")
				new prize.equipment_path(drop_location())
		else
			to_chat(usr, "<span class='warning'>Error: Please insert a valid ID!</span>")
			flick(icon_deny, src)
	updateUsrDialog()

