//? moon phases

#define MOON_PHASE_NEW_MOON			"new moon"
#define MOON_PHASE_WAXING_CRESCENT	"waxing crescent"
#define MOON_PHASE_FIRST_QUARTER	"first quarter"
#define MOON_PHASE_WAXING_GIBBOUS	"waxing gibbous"
#define MOON_PHASE_FULL_MOON		"full moon"
#define MOON_PHASE_WANING_GIBBOUS	"waning gibbous"
#define MOON_PHASE_LAST_QUARTER		"last quarter"
#define MOON_PHASE_WANING_CRESCENT	"waning crescent"

GLOBAL_LIST_INIT(moon_phases, list(
	MOON_PHASE_NEW_MOON,
	MOON_PHASE_WAXING_CRESCENT,
	MOON_PHASE_FIRST_QUARTER,
	MOON_PHASE_WAXING_GIBBOUS,
	MOON_PHASE_FULL_MOON,
	MOON_PHASE_WANING_GIBBOUS,
	MOON_PHASE_LAST_QUARTER,
	MOON_PHASE_WANING_CRESCENT,
))

GLOBAL_LIST_INIT(moon_phase_strengths, list(
	MOON_PHASE_NEW_MOON = 0,
	MOON_PHASE_WAXING_CRESCENT = 0.25,
	MOON_PHASE_FIRST_QUARTER = 0.5,
	MOON_PHASE_WAXING_GIBBOUS = 0.75,
	MOON_PHASE_FULL_MOON = 1,
	MOON_PHASE_WANING_GIBBOUS = 0.75,
	MOON_PHASE_LAST_QUARTER = 0.5,
	MOON_PHASE_WANING_CRESCENT = 0.25,
))

#warn how to do this with cycles
