/obj/machinery/vending/dinnerware
	products = list(
		/obj/item/tray = 8,
		/obj/item/material/kitchen/utensil/fork = 6,
		/obj/item/material/knife/plastic = 6,
		/obj/item/material/kitchen/utensil/spoon = 6,
		/obj/item/material/knife = 3,
		/obj/item/material/kitchen/rollingpin = 2,
		/obj/item/reagent_containers/food/drinks/glass2/square = 8,
		/obj/item/reagent_containers/food/drinks/glass2/shake = 8,
		/obj/item/glass_extra/stick = 15,
		/obj/item/glass_extra/straw = 15,
		/obj/item/clothing/suit/chef/classic = 2,
		/obj/item/storage/toolbox/lunchbox = 3,
		/obj/item/storage/toolbox/lunchbox/heart = 3,
		/obj/item/storage/toolbox/lunchbox/cat = 3,
		/obj/item/storage/toolbox/lunchbox/nt = 3,
		/obj/item/storage/toolbox/lunchbox/mars = 3,
		/obj/item/storage/toolbox/lunchbox/cti = 3,
		/obj/item/storage/toolbox/lunchbox/nymph = 3,
		/obj/item/storage/toolbox/lunchbox/syndicate = 3,
		/obj/item/trash/bowl = 30,
		/obj/item/reagent_containers/cooking_container/oven = 5,
		/obj/item/reagent_containers/cooking_container/fryer = 4
	)