/obj/machinery/vending/boozeomat
	name = "Booze-O-Mat"
	desc = "A technological marvel, supposedly able to mix just the mixture you'd like to drink the moment you ask for one."
	icon_state = "boozeomat"
	icon_deny = "boozeomat-deny"
	products = list(
		/obj/item/reagent_containers/food/drinks/glass2/square = 10,
		/obj/item/reagent_containers/food/drinks/glass2/rocks = 10,
		/obj/item/reagent_containers/food/drinks/glass2/shake = 10,
		/obj/item/reagent_containers/food/drinks/glass2/cocktail = 10,
		/obj/item/reagent_containers/food/drinks/glass2/shot = 10,
		/obj/item/reagent_containers/food/drinks/glass2/pint = 10,
		/obj/item/reagent_containers/food/drinks/glass2/mug = 10,
		/obj/item/reagent_containers/food/drinks/glass2/wine = 10,
		/obj/item/reagent_containers/food/drinks/glass2/pitcher = 10,
		/obj/item/reagent_containers/food/drinks/metaglass = 25,
		/obj/item/reagent_containers/food/drinks/bottle/gin = 5,
		/obj/item/reagent_containers/food/drinks/bottle/absinthe = 5,
		/obj/item/reagent_containers/food/drinks/bottle/bluecuracao = 5,
		/obj/item/reagent_containers/food/drinks/bottle/cognac = 5,
		/obj/item/reagent_containers/food/drinks/bottle/grenadine = 5,
		/obj/item/reagent_containers/food/drinks/bottle/kahlua = 5,
		/obj/item/reagent_containers/food/drinks/bottle/melonliquor = 5,
		/obj/item/reagent_containers/food/drinks/bottle/peppermintschnapps = 5,
		/obj/item/reagent_containers/food/drinks/bottle/peachschnapps = 5,
		/obj/item/reagent_containers/food/drinks/bottle/lemonadeschnapps = 5,
		/obj/item/reagent_containers/food/drinks/bottle/rum = 5,
		/obj/item/reagent_containers/food/drinks/bottle/whiterum = 5,
		/obj/item/reagent_containers/food/drinks/bottle/sake = 5,
		/obj/item/reagent_containers/food/drinks/bottle/specialwhiskey = 5,
		/obj/item/reagent_containers/food/drinks/bottle/tequila = 5,
		/obj/item/reagent_containers/food/drinks/bottle/vermouth = 5,
		/obj/item/reagent_containers/food/drinks/bottle/vodka = 5,
		/obj/item/reagent_containers/food/drinks/bottle/whiskey = 5,
		/obj/item/reagent_containers/food/drinks/bottle/wine = 5,
		/obj/item/reagent_containers/food/drinks/bottle/whitewine = 5,
		/obj/item/reagent_containers/food/drinks/bottle/bitters = 5,
		/obj/item/reagent_containers/food/drinks/bottle/victory_gin = 3,
		/obj/item/reagent_containers/food/drinks/bottle/messa_mead = 3,
		/obj/item/reagent_containers/food/drinks/bottle/small/ale = 15,
		/obj/item/reagent_containers/food/drinks/bottle/small/beer = 15,
		/obj/item/reagent_containers/food/drinks/bottle/small/cider = 15,
		/obj/item/reagent_containers/food/drinks/bottle/small/alcsassafras = 15,
		/obj/item/reagent_containers/food/drinks/bottle/orangejuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/tomatojuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/limejuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/lemonjuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/applejuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/milk = 5,
		/obj/item/reagent_containers/food/drinks/bottle/cream = 5,
		/obj/item/reagent_containers/food/drinks/bottle/cola = 5,
		/obj/item/reagent_containers/food/drinks/bottle/space_up = 5,
		/obj/item/reagent_containers/food/drinks/bottle/space_mountain_wind = 5,
		/obj/item/reagent_containers/food/drinks/bottle/champagne/jericho = 1,
		/obj/item/reagent_containers/food/drinks/bottle/champagne = 3,
		/obj/item/reagent_containers/food/drinks/bottle/coconutmilk = 5,
		/obj/item/reagent_containers/food/drinks/bottle/unathijuice = 2,
		/obj/item/reagent_containers/food/drinks/cans/sodawater = 15,
		/obj/item/reagent_containers/food/drinks/cans/tonic = 15,
		/obj/item/reagent_containers/food/drinks/cans/gingerale = 15,
		/obj/item/reagent_containers/food/drinks/flask/barflask = 5,
		/obj/item/reagent_containers/food/drinks/flask/vacuumflask = 5,
		/obj/item/reagent_containers/food/drinks/ice = 10,
		/obj/item/reagent_containers/food/drinks/tea = 15,
		/obj/item/reagent_containers/food/condiment/small/packet/matchapowder = 5,
		/obj/item/reagent_containers/food/condiment/small/packet/taropowder = 5,
		/obj/item/glass_extra/stick = 30,
		/obj/item/glass_extra/straw = 30,
		/obj/item/storage/single_use/med_pouch/overdose = 2,
	)
	contraband = list()
	vend_delay = 15
	idle_power_usage = 211 //refrigerator - believe it or not, this is actually the average power consumption of a refrigerated vending machine according to NRCan.
	product_slogans = "I hope nobody asks me for a bloody cup o' tea...;Alcohol is humanity's friend. Would you abandon a friend?;Quite delighted to serve you!;Is nobody thirsty on this station?"
	product_ads = "Drink up!;Booze is good for you!;Alcohol is humanity's best friend.;Quite delighted to serve you!;Care for a nice, cold beer?;Nothing cures you like booze!;Have a sip!;Have a drink!;Have a beer!;Beer is good for you!;Only the finest alcohol!;Best quality booze since 2053!;Award-winning wine!;Maximum alcohol!;Man loves beer.;A toast for progress!"
	req_access = list(ACCESS_GENERAL_BAR)
	req_log_access = ACCESS_GENERAL_BAR
	has_logs = 1

/obj/machinery/vending/cafe
	name = "Cafe vendor"
	desc = "A vendor with glasses, cups, juice, pastries, and so on."
	icon_state = "cafe"
	icon_deny = "boozeomat-deny"
	products = list(
		/obj/item/reagent_containers/food/drinks/glass2/square = 10,
		/obj/item/reagent_containers/food/drinks/glass2/rocks = 10,
		/obj/item/reagent_containers/food/drinks/glass2/shake = 10,
		/obj/item/reagent_containers/food/drinks/glass2/cocktail = 10,
		/obj/item/reagent_containers/food/drinks/glass2/shot = 10,
		/obj/item/reagent_containers/food/drinks/glass2/pint = 10,
		/obj/item/reagent_containers/food/drinks/glass2/mug = 10,
		/obj/item/reagent_containers/food/drinks/glass2/wine = 10,
		/obj/item/reagent_containers/food/drinks/glass2/pitcher = 10,
		/obj/item/reagent_containers/food/drinks/cup = 10,
		/obj/item/reagent_containers/food/drinks/metaglass = 25,
		/obj/item/reagent_containers/food/drinks/bottle/grenadine = 5,
		/obj/item/reagent_containers/food/drinks/bottle/orangejuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/tomatojuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/limejuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/lemonjuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/applejuice = 5,
		/obj/item/reagent_containers/food/drinks/bottle/milk = 5,
		/obj/item/reagent_containers/food/drinks/bottle/cream = 5,
		/obj/item/reagent_containers/food/drinks/bottle/cola = 5,
		/obj/item/reagent_containers/food/drinks/bottle/space_up = 5,
		/obj/item/reagent_containers/food/drinks/bottle/space_mountain_wind = 5,
		/obj/item/reagent_containers/food/drinks/bottle/coconutmilk = 5,
		/obj/item/reagent_containers/food/drinks/bottle/unathijuice = 2,
		/obj/item/reagent_containers/food/drinks/cans/sodawater = 15,
		/obj/item/reagent_containers/food/drinks/cans/tonic = 15,
		/obj/item/reagent_containers/food/drinks/cans/gingerale = 15,
		/obj/item/reagent_containers/food/drinks/flask/barflask = 5,
		/obj/item/reagent_containers/food/drinks/flask/vacuumflask = 5,
		/obj/item/reagent_containers/food/drinks/ice = 10,
		/obj/item/reagent_containers/food/drinks/tea = 15,
		/obj/item/reagent_containers/food/condiment/small/packet/matchapowder = 5,
		/obj/item/reagent_containers/food/condiment/small/packet/taropowder = 5,
		/obj/item/glass_extra/stick = 30,
		/obj/item/glass_extra/straw = 30,
		/obj/item/storage/single_use/med_pouch/overdose = 2,
		/obj/item/reagent_containers/food/drinks/coffee_cup = 10,
		/obj/item/reagent_containers/food/condiment/small/packet/creamer = 20,
		/obj/item/reagent_containers/food/condiment/small/packet/sugar = 20,
		/obj/item/reagent_containers/food/condiment/small/packet/astrotame = 20,
	)
	contraband = list()
	vend_delay = 15
	idle_power_usage = 211 //refrigerator - believe it or not, this is actually the average power consumption of a refrigerated vending machine according to NRCan.

/obj/machinery/vending/dinnerware
	name = "Dinnerware"
	desc = "A kitchen and restaurant equipment vendor."
	product_ads = "Mm, food stuffs!;Food and food accessories.;Get your plates!;You like forks?;I like forks.;Woo, utensils.;You don't really need these..."
	icon_state = "dinnerware"
	products = list(
		/obj/item/tray = 8,
		/obj/item/material/kitchen/utensil/fork = 6,
		/obj/item/material/knife/plastic = 6,
		/obj/item/material/kitchen/utensil/spoon = 6,
		/obj/item/material/knife = 3,
		/obj/item/material/kitchen/rollingpin = 2,
		/obj/item/reagent_containers/food/drinks/glass2/square = 8,
		/obj/item/reagent_containers/food/drinks/glass2/shake = 8,
		/obj/item/glass_extra/stick = 15,
		/obj/item/glass_extra/straw = 15,
		/obj/item/clothing/suit/chef/classic = 2,
		/obj/item/storage/toolbox/lunchbox = 3,
		/obj/item/storage/toolbox/lunchbox/heart = 3,
		/obj/item/storage/toolbox/lunchbox/cat = 3,
		/obj/item/storage/toolbox/lunchbox/nt = 3,
		/obj/item/storage/toolbox/lunchbox/mars = 3,
		/obj/item/storage/toolbox/lunchbox/cti = 3,
		/obj/item/storage/toolbox/lunchbox/nymph = 3,
		/obj/item/storage/toolbox/lunchbox/syndicate = 3,
		/obj/item/storage/toolbox/lunchbox/cyancowgirl = 3,
		/obj/item/trash/bowl = 30,
		/obj/item/reagent_containers/cooking_container/oven = 5,
		/obj/item/reagent_containers/cooking_container/fryer = 4,
	)
	contraband = list(
		/obj/item/material/knife/butch = 2,
	)

/obj/machinery/vending/fishing
	name = "Loot Trawler"
	desc = "A special vendor for fishing equipment."
	product_ads = "Tired of trawling across the ocean floor? Get our loot!;Chum and rods.;Don't get baited into fishing without us!;Baby is your star-sign pisces? We'd make a perfect match.;Do not fear, plenty to catch around here.;Don't get reeled in helplessly, get your own rod today!"
	icon_state = "fishvendor"
	products = list(
		/obj/item/fishing_rod = 10,
		/obj/item/fishing_hook = 20,
		/obj/item/fishing_line = 20,
		/obj/item/fishing_hook/magnet = 10,
		/obj/item/fishing_hook/rescue = 10,
		/obj/item/fishing_hook/shiny = 10,
		/obj/item/fishing_hook/weighted = 10,
		/obj/item/fishing_line = 20,
		/obj/item/fishing_line/bouncy = 10,
		/obj/item/fishing_line/reinforced = 10,
		/obj/item/bait_can/worm = 80,
		/obj/item/aquarium_kit = 20,
		/obj/item/storage/box/aquarium_props = 20,
		/obj/item/storage/fish_case = 30,
		/obj/item/book/fish_catalog = 20,
	)
	price_default = 10
	prices = list(
		/obj/item/fishing_rod = 50,
		/obj/item/bait_can/worm = 5,
		/obj/item/aquarium_kit = 50,
		/obj/item/storage/box/aquarium_props = 25,
	)
