#warn obliterate this file
/obj/machinery/account_database
	icon = 'icons/obj/computer.dmi'
	icon_state = "account_computer"
	req_one_access = list(ACCESS_COMMAND_BANKING, ACCESS_CENTCOM_ADMIRAL)

/obj/machinery/account_database/proc/accounting_letterhead(report_name)
	return {"
		<center><h1><b>[report_name]</b></h1></center>
		<center><small><i>[station_name()] Accounting Report</i></small></center>
		<hr>
		<u>Generated By:</u> [held_card.registered_name], [held_card.assignment]<br>
	"}

/obj/machinery/account_database/nano_ui_interact(mob/user, ui_key="main", var/datum/nanoui/ui = null, var/force_open = 1)
	user.set_machine(src)

	var/data[0]
	data["src"] = "\ref[src]"
	data["id_inserted"] = !!held_card
	data["id_card"] = held_card ? "[held_card.registered_name], [held_card.assignment]" : "-----"
	data["access_level"] = get_access_level()
	data["machine_id"] = machine_id
	data["detailed_account_view"] = !!detailed_account_view
	data["transactions"] = null
	data["accounts"] = null

	var/list/accounts[0]
	for(var/i=1, i<=GLOB.all_money_accounts.len, i++)
		var/datum/economy_account/D = GLOB.all_money_accounts[i]
		accounts.Add(list(list(\
			"account_id"=D.account_id,\
			"owner_name"=D.owner_name,\
			"suspended"=D.suspended ? "SUSPENDED" : "",\
			"account_index"=i)))

	if (accounts.len > 0)
		data["accounts"] = accounts

	ui = SSnanoui.try_update_ui(user, src, ui_key, ui, data, force_open)
	if (!ui)
		ui = new(user, src, ui_key, "accounts_terminal.tmpl", src.name, 400, 640)
		ui.set_initial_data(data)
		ui.open()

/obj/machinery/account_database/Topic(href, href_list)
	if(..())
		return 1

	var/datum/nanoui/ui = SSnanoui.get_open_ui(usr, src, "main")

	if(href_list["choice"])
		switch(href_list["choice"])
			if("toggle_suspension")
				if(detailed_account_view)
					detailed_account_view.suspended = !detailed_account_view.suspended
					callHook("change_account_status", list(detailed_account_view))

			if("finalise_create_account")
				var/account_name = href_list["holder_name"]
				var/starting_funds = max(text2num(href_list["starting_funds"]), 0)

				starting_funds = clamp(starting_funds, 0, GLOB.station_account.money)	// Not authorized to put the station in debt.
				starting_funds = min(starting_funds, fund_cap)						// Not authorized to give more than the fund cap.

				create_account(account_name, starting_funds, src)
				if(starting_funds > 0)
					//subtract the money
					GLOB.station_account.money -= starting_funds

					//create a transaction log entry
					var/trx = create_transation(account_name, "New account activation", "([starting_funds])")
					GLOB.station_account.transaction_log.Add(trx)

					creating_new_account = 0
					ui.close()

				creating_new_account = 0
			if("insert_card")
				if(held_card)
					held_card.loc = src.loc

					if(ishuman(usr) && !usr.get_active_held_item())
						usr.put_in_hands(held_card)
					held_card = null

				else
					var/obj/item/I = usr.get_active_held_item()
					if (istype(I, /obj/item/card/id))
						var/obj/item/card/id/C = I
						if(!usr.attempt_insert_item_for_installation(C, src))
							return
						held_card = C

			if("revoke_payroll")
				var/funds = detailed_account_view.money
				var/account_trx = create_transation(GLOB.station_account.owner_name, "Revoke payroll", "([funds])")
				var/station_trx = create_transation(detailed_account_view.owner_name, "Revoke payroll", funds)

				GLOB.station_account.money += funds
				detailed_account_view.money = 0

				detailed_account_view.transaction_log.Add(account_trx)
				GLOB.station_account.transaction_log.Add(station_trx)

				callHook("revoke_payroll", list(detailed_account_view))

			if("print")
				var/text
				var/obj/item/paper/P = new(loc)
				if (detailed_account_view)
					P.name = "account #[detailed_account_view.account_id] details"
					var/title = "Account #[detailed_account_view.account_id] Details"
					text = {"
						[accounting_letterhead(title)]
						"}

				else
	return 1
