/**
 * Species IDs
 */
#define SPECIES_ID_ADHERENT "adherent"
#define SPECIES_ID_AKULA "akula"
#define SPECIES_ID_ALRAUNE "alraune"
#define SPECIES_ID_APIDAEN "apidaen"
#define SPECIES_ID_AURIL "auril"
#define SPECIES_ID_CUSTOM "custom"
#define SPECIES_ID_DIONA "diona"
#define SPECIES_ID_DREMACHIR "dremachir"
#define SPECIES_ID_FARWA "farwa"
#define SPECIES_ID_GOLEM "golem"
#define SPECIES_ID_HARPY "harpy"
#define SPECIES_ID_HUMAN "human"
	#define SPECIES_ID_HUMAN_GRAV "human_grav"
	#define SPECIES_ID_HUMAN_SPACE "human_space"
	#define SPECIES_ID_HUMAN_VAT "human_vat"
#define SPECIES_ID_MONKEY "monkey"
#define SPECIES_ID_MOTH "moth"
	#define SPECIES_ID_MOTH_DARK "moth_dark"
	#define SPECIES_ID_MOTH_LIGHT "moth_light"
#define SPECIES_ID_NARAMADI "naramadi"
#define SPECIES_ID_NEAERA "neaera"
#define SPECIES_ID_NEVREAN "nevrean"
#define SPECIES_ID_PHORONOID "phoronoid"
#define SPECIES_ID_PROMETHEAN "promethean"
#define SPECIES_ID_PROTEAN "protean"
#define SPECIES_ID_RAPALA "rapala"
#define SPECIES_ID_REPLICANT "replicant"
	#define SPECIES_ID_REPLICANT_ALPHA "replicant_alpha"
	#define SPECIES_ID_REPLICANT_BETA "replicant_beta"
#define SPECIES_ID_SCORI "scori"
#define SPECIES_ID_SERGLING "sergling"
#define SPECIES_ID_SHADEKIN "shadekin"
#define SPECIES_ID_SHADEKIN_BLACK "shadekin_black"
#define SPECIES_ID_SHADOW "shadow"
#define SPECIES_ID_SKELETON "skeleton"
#define SPECIES_ID_SKRELL "skrell"
#define SPECIES_ID_SOBAKA "sobaka"
#define SPECIES_ID_SPARRA "sparra"
#define SPECIES_ID_STOK "stok"
#define SPECIES_ID_TAJARAN "tajaran"
#define SPECIES_ID_TESHARI "teshari"
#define SPECIES_ID_UNATHI "unathi"
#define SPECIES_ID_UNATHI_DIGI "unathidigi"
#define SPECIES_ID_VASILISSAN "vasilissan"
#define SPECIES_ID_VIRTUAL_REALITY "virtual_reality"
	#define SPECIES_ID_VIRTUAL_REALITY_DIONA "virtual_reality_diona"
	#define SPECIES_ID_VIRTUAL_REALITY_HUMAN "virtual_reality_human"
	#define SPECIES_ID_VIRTUAL_REALITY_MONKEY "virtual_reality_monkey"
	#define SPECIES_ID_VIRTUAL_REALITY_SKELETON "virtual_reality_skeleton"
	#define SPECIES_ID_VIRTUAL_REALITY_SKRELL "virtual_reality_skrell"
	#define SPECIES_ID_VIRTUAL_REALITY_TAJARAN "virtual_reality_tajaran"
	#define SPECIES_ID_VIRTUAL_REALITY_TESHARI "virtual_reality_teshari"
	#define SPECIES_ID_VIRTUAL_REALITY_UNATHI "virtual_reality_unathi"
	#define SPECIES_ID_VIRTUAL_REALITY_VOX "virtual_reality_vox"
#define SPECIES_ID_VOX "vox"
#define SPECIES_ID_VULPKANIN "vulpkanin"
#define SPECIES_ID_WEREBEAST "werebeast"
#define SPECIES_ID_WOLPIN "wolpin"
#define SPECIES_ID_XENOCHIMERA "xenochimera"
#define SPECIES_ID_XENOMORPH "xenomorph"
	#define SPECIES_ID_XENOMORPH_DRONE "xenomorph_drone"
	#define SPECIES_ID_XENOMORPH_HUNTER "xenomorph_hunter"
	#define SPECIES_ID_XENOMORPH_QUEEN "xenomorph_queen"
	#define SPECIES_ID_XENOMORPH_SENTINEL "xenomorph_sentinel"
#define SPECIES_ID_XENOHYBRID "xenohybrid"
#define SPECIES_ID_ZADDAT "zaddat"
#define SPECIES_ID_ZORREN "zorren"
	#define SPECIES_ID_ZORREN_HIGH "zorren_high"
	#define SPECIES_ID_ZORREN_FLAT "zorren_flat"

/**
 * !It is important to note that these are not only used for the name of the species.
 * !They are also used as ID Tags for various otther things, such as character saves!
 * -Zandario
 * TODO: give rest of species ids so we don't need to do this. ^
 */
#define SPECIES_ADHERENT "Adherent"
#define SPECIES_AKULA "Akula"
#define SPECIES_ALRAUNE "Alraune"
#define SPECIES_APIDAEN "Apidaen"
#define SPECIES_AURIL "Auril"
#define SPECIES_CUSTOM "Custom Species"
#define SPECIES_DIONA "Diona"
#define SPECIES_DREMACHIR "Dremachir"
#define SPECIES_GOLEM "Golem"
#define SPECIES_HUMAN "Human"
#define SPECIES_HUMAN_GRAV "grav-adapted Human"
#define SPECIES_HUMAN_SPACER "space-adapted Human"
#define SPECIES_HUMAN_VATBORN "Vatborn"
#define SPECIES_MONKEY "Monkey"
#define SPECIES_MONKEY_AKULA "Sobaka"
#define SPECIES_MONKEY_NEVREAN "Sparra"
#define SPECIES_MONKEY_SERGAL "Saru"
#define SPECIES_MONKEY_SKRELL "Neaera"
#define SPECIES_MONKEY_TAJ "Farwa"
#define SPECIES_MONKEY_UNATHI "Stok"
#define SPECIES_MONKEY_VULPKANIN "Wolpin"
#define SPECIES_MOTH "Dnin-Nepid"
#define SPECIES_MOTH_DARK "Dnin-Nepid (Dark-Adapted)"
#define SPECIES_MOTH_LIGHT "Dnin-Nepid (Light-Adapted)"
#define SPECIES_NEVREAN "Nevrean"
#define SPECIES_PHORONOID "Phoronoid"
#define SPECIES_PROMETHEAN "Promethean"
#define SPECIES_PROTEAN "Protean"
#define SPECIES_RAPALA "Rapala"
#define SPECIES_REPLICANT "Replicant"
#define SPECIES_REPLICANT_ALPHA "Alpha Replicant"
#define SPECIES_REPLICANT_BETA "Beta Replicant"
#define SPECIES_SCORI "Scori"
#define SPECIES_SERGAL "Naramad"
#define SPECIES_SHADEKIN "Shadekin"
#define SPECIES_SHADEKIN_CREW "Black-Eyed Shadekin"
#define SPECIES_SHADOW "Shadow"
#define SPECIES_SKELETON "Skeleton"
#define SPECIES_SKRELL "Skrell"
#define SPECIES_TAJ "Tajara"
#define SPECIES_TESHARI "Teshari"
#define SPECIES_UNATHI "Unathi"
#define SPECIES_UNATHI_DIGI "Digitigrade Unathi"
#define SPECIES_VASILISSAN "Vasilissan"
#define SPECIES_VOX "Vox"
#define SPECIES_VR "Virtual Reality Avatar"
#define SPECIES_VR_DIONA "Virtual Reality Diona"
#define SPECIES_VR_HUMAN "Virtual Reality Human"
#define SPECIES_VR_MONKEY "Virtual Reality Monkey"
#define SPECIES_VR_SKELETON "Virtual Reality Skeleton"
#define SPECIES_VR_SKRELL "Virtual Reality Skrell"
#define SPECIES_VR_TAJ "Virtual Reality Tajara"
#define SPECIES_VR_TESHARI "Virtual Reality Teshari"
#define SPECIES_VR_UNATHI "Virtual Reality Unathi"
#define SPECIES_VR_VOX "Virtual Reality Vox"
#define SPECIES_VULPKANIN "Vulpkanin"
#define SPECIES_WEREBEAST "Werebeast"
#define SPECIES_XENO "Xenomorph"
#define SPECIES_XENO_DRONE "Xenomorph Drone"
#define SPECIES_XENO_HUNTER "Xenomorph Hunter"
#define SPECIES_XENO_QUEEN "Xenomorph Queen"
#define SPECIES_XENO_SENTINEL "Xenomorph Sentinel"
#define SPECIES_XENOCHIMERA "Xenochimera"
#define SPECIES_XENOHYBRID "Xenomorph Hybrid"
#define SPECIES_ZADDAT "Zaddat"
#define SPECIES_ZORREN_FLAT "Flatland Zorren"
#define SPECIES_ZORREN_HIGH "Highlander Zorren"



//! ## SHADEKIN DEFINES
#define NOT_WHILE_SHIFTED  1
#define ONLY_WHILE_SHIFTED 2
#define SHIFTED_OR_NOT     3

#define BLUE_EYES   1
#define RED_EYES    2
#define PURPLE_EYES 3
#define YELLOW_EYES 4
#define GREEN_EYES  5
#define ORANGE_EYES 6

#define AB_PHASE_SHIFTED (1<<0)
#define AB_SHADE_REGEN   (1<<1)
