#define SOFT_DARKSIGHT_15X15_ICON 'icons/screen/rendering/darksight_15x15.dmi'

#define SOFT_DARKSIGHT_RANGE_DEFAULT 32
#define SOFT_DARKSIGHT_RANGE_TIER_1 64
#define SOFT_DARKSIGHT_RANGE_TIER_2 96
#define SOFT_DARKSIGHT_RANGE_TIER_3 128

/// above this, we give them a full screen overlay instead of trying to transform an atom.
#define SOFT_DARKSIGHT_UNLIMITED_THRESHOLD (WORLD_ICON_SIZE * 20)

#define SOFT_DARKSIGHT_ALPHA_DEFAULT 75
#define SOFT_DARKSIGHT_ALPHA_TIER_1 130
#define SOFT_DARKSIGHT_ALPHA_TIER_2 140
#define SOFT_DARKSIGHT_ALPHA_TIER_3 140

#define DARKSIGHT_PRIORITY_INNATE -1000
#define DARKSIGHT_PRIORITY_EYES 0
#define DARKSIGHT_PRIORITY_MODIFIER 250
#define DARKSIGHT_PRIORITY_GLASSES 500
#define DARKSIGHT_PRIORITY_VISOR 750
#define DARKSIGHT_PRIORITY_DEFAULT 1000
