# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: Auto Changelog
on:
  pull_request_target:
    types: [opened, edited, synchronize]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto_changelog:
    runs-on: ubuntu-latest
    outputs:
      verbosity: verbose
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run auto changelog
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_EVENT: ${{ toJson(github.event)}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      run: |
        node -e '
        const core = import("@actions/core")
        const github = import("@actions/github")
        const { context } = github;
        const event = JSON.parse(process.env.GITHUB_EVENT);
        import("./tools/pull_request_hooks/autoChangelog.js")
          .then(module => module.processAutoChangelog({ github: github, context: {...context, payload: event} }))
        '
