# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: Auto Changelog
on:
  pull_request_target:
    types: [opened, edited, synchronize]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto_changelog:
    runs-on: ubuntu-latest
    outputs:
      verbosity: verbose
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run auto changelog
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_EVENT: $({ toJson(github.event)})
      run: |
        node -e '
        const github = JSON.parse(process.env.GITHUB_CONTEXT);
        const event = JSON.parse(process.env.GITHUB_EVENT);
        import("./tools/pull_request_hooks/autoChangelog.js")
          .then(module => module.processAutoChangelog({ github: github, context: {payload: event} }))
        '


GITHUB_CONTEXT: {
  "token": "***",
  "job": "auto_changelog",
  "ref": "refs/pull/6488/merge",
  "sha": "25c6138976d7f5c7567531b6ac3bd4c624ba0868",
  "repository": "Citadel-Station-13/Citadel-Station-13-RP",
  "repository_owner": "Citadel-Station-13",
  "repository_owner_id": "11160241",
  "repositoryUrl": "git://github.com/Citadel-Station-13/Citadel-Station-13-RP.git",
  "run_id": "9338978545",
  "run_number": "1662",
  "retention_days": "90",
  "run_attempt": "1",
  "artifact_cache_size_limit": "10",
  "repository_visibility": "public",
  "repo-self-hosted-runners-disabled": false,
  "enterprise-managed-business-id": "",
  "repository_id": "132374308",
  "actor_id": "58342752",
  "actor": "TheLordME",
  "triggering_actor": "TheLordME",
  "workflow": "Auto Changelog",
  "head_ref": "another_auotchangelog",
  "base_ref": "master",
  "event_name": "pull_request",
  "event": {
    "action": "synchronize",
    "after": "dd6c608d21521ff0b87bbf9b82daac0c8053dc9d",
    "before": "4d6732bb967dfb70ebe74f6b1e9a50b4644a7e6d",
    "number": 6488,
    "organization": {
      "avatar_url": "https://avatars.githubusercontent.com/u/11160241?v=4",
      "description": null,
      "events_url": "https://api.github.com/orgs/Citadel-Station-13/events",
      "hooks_url": "https://api.github.com/orgs/Citadel-Station-13/hooks",
      "id": 11160241,
      "issues_url": "https://api.github.com/orgs/Citadel-Station-13/issues",
      "login": "Citadel-Station-13",
      "members_url": "https://api.github.com/orgs/Citadel-Station-13/members{/member}",
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjExMTYwMjQx",
      "public_members_url": "https://api.github.com/orgs/Citadel-Station-13/public_members{/member}",
      "repos_url": "https://api.github.com/orgs/Citadel-Station-13/repos",
      "url": "https://api.github.com/orgs/Citadel-Station-13"
    },
    "pull_request": {
