# Creates an entry in html/changelogs automatically, to eventually be compiled by compile_changelogs
name: Auto Changelog
on:
  pull_request_target:
    types: [opened, edited, synchronize]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  auto_changelog:
    runs-on: ubuntu-latest
    outputs:
      verbosity: verbose
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run auto changelog
      run: |
        node -e 'process.env.GITHUB_CONTEXT = JSON.stringify(process.env.GITHUB_CONTEXT); process.env.GITHUB_EVENT = JSON.stringify(process.env.GITHUB_EVENT); import("./tools/pull_request_hooks/autoChangelog.js").then(module => module.processAutoChangelog(JSON.parse(process.env.GITHUB_CONTEXT), JSON.parse(process.env. GITHUB_EVENT)))'
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_EVENT: $({ toJson(github.event)})

