name: 'Check for merge conflicts'
on:
  push:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository == 'Citadel-Station-13/Citadel-Station-13-RP'
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v3
        with:
          CONFLICT_LABEL_NAME: 'Merge Conflict'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 12
          WAIT_MS: 10000
          conflict_comment: ''
