name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  stale:

    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "This PR has been inactive for long enough to be automatically marked as stale. This means it is at risk of being auto closed in ~ two week, please address any outstanding review items and ensure your PR is finished, if these are all true and you are auto-staled anyway, you need to actively ask maintainers if your PR will be merged. Once you have done any of the previous actions then you should request a maintainer remove the stale label on your PR, to reset the stale timer. If you feel no maintainer will respond in that time, you may wish to close this PR youself, while you seek maintainer comment, as you will then be able to reopen the PR yourself"
        days-before-stale: 14
        days-before-close: 14
        stale-pr-label: 'Stale'
        close-pr-label: 'Closed By Stale'
        close-pr-message: 'This PR was closed due to inactivity, if you feel this was done in error, please request a maintainer remove the stale label on your PR, to reset the stale timer.'
        days-before-issue-stale: -1
        stale-issue-label: 'Cleanup Flagged'
        remove-issue-stale-when-updated: false
        exempt-draft-pr: true
        exempt-pr-labels: 'Good First PR,Work in Progress,Do Not Merge,Stale Exempt'
        operations-per-run: 300
